
#
# Build settings that are independent of compiler version.
#

# Base of Trilinos/cmake/ctest then BUILD_DIR_NAME

SET( CTEST_DASHBOARD_ROOT "${TRILINOS_CMAKE_DIR}/../../${BUILD_DIR_NAME}" )

SET( CTEST_NOTES_FILES "${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}" )

SET( CTEST_BUILD_FLAGS "-j8 -i" )

SET_DEFAULT( CTEST_PARALLEL_LEVEL "8" )

SET_DEFAULT( Trilinos_ENABLE_SECONDARY_STABLE_CODE ON)

# Only turn on PyTrilinos for shared libraries
SET_DEFAULT( Trilinos_EXCLUDE_PACKAGES ${EXTRA_EXCLUDE_PACKAGES} PyTrilinos TriKota Optika)
  
SET( EXTRA_SYSTEM_CONFIGURE_OPTIONS
  "-DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}"
  "-DTrilinos_ENABLE_DEPENCENCY_UNIT_TESTS:BOOL=OFF"
  "-DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE"
  "-DTrilinos_ENABLE_TriKota:BOOL=OFF"
  "-DTPL_ENABLE_BinUtils=ON"
  "-DTPL_ENABLE_Matio=OFF"
  "-DIntrepid_ENABLE_DEBUG_INF_CHECK=OFF"
  )

