TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES Anasazi Kokkos Intrepid2 Shards SEACASIoss STKUtil STKIO STKMesh STKExprEval STKSearch STKTransfer STKTopology Teuchos Zoltan
  LIB_OPTIONAL_TPLS OpenNURBS
  )
