TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES Intrepid2 SEACASIoss STKUtil STKIO STKMesh STKExprEval STKSearch STKTransfer Zoltan
  TEST_OPTIONAL_PACKAGES Gtest
  LIB_OPTIONAL_TPLS OpenNURBS
  )
