TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES SEACASIoss STKUtil STKIO STKMesh STKExprEval STKSearch STKTransfer Intrepid
  TEST_OPTIONAL_PACKAGES Gtest
  LIB_OPTIONAL_TPLS OpenNURBS
  )
