#ifndef MUELU_SUBBLOCKUNAMALGAMATIONFACTORY_FWD_HPP
#define MUELU_SUBBLOCKUNAMALGAMATIONFACTORY_FWD_HPP

namespace MueLu {
  template <class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node, class LocalMatOps>
  class SubBlockUnAmalgamationFactory;
}

#ifndef MUELU_SUBBLOCKUNAMALGAMATIONFACTORY_SHORT
#define MUELU_SUBBLOCKUNAMALGAMATIONFACTORY_SHORT
#endif

#endif // MUELU_SUBBLOCKUNAMALGAMATIONFACTORY_FWD_HPP
