#ifndef MUELU_AMESOSSMOOTHER_FWD_HPP
#define MUELU_AMESOSSMOOTHER_FWD_HPP

namespace MueLu {
  class AmesosSmoother;
}

#ifndef MUELU_AMESOSSMOOTHER_SHORT
#define MUELU_AMESOSSMOOTHER_SHORT
#endif

#endif // MUELU_AMESOSSMOOTHER_FWD_HPP
