SET(LIB_REQUIRED_DEP_PACKAGES STKUtil STKSearch)
SET(LIB_OPTIONAL_DEP_PACKAGES STKMiddle_mesh)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

