# This file contains the options needed to both run the pull request testing
# for Trilinos for the CUDA 10.1.105 UVM pull request testing builds, and to reproduce
# the errors reported by those builds. Prior to using this this file, the
# appropriate set of modules must be loaded and path must be augmented.
# (See the sems/PullRequestCuda10.1.105uvmTestingEnv.sh files.)

# Usage: cmake -C PullRequestLinuxCUDA10.1.105uvmTestingSettings.cmake

set (CMAKE_CXX_STANDARD "14" CACHE STRING "Set C++ standard to C++14")

# Misc options typically added by CI testing mode in TriBITS

# Use the below option only when submitting to the dashboard
set (CTEST_USE_LAUNCHERS ON CACHE BOOL "Set by default for PR testing")

# Options necessary for CUDA build
set (TPL_ENABLE_MPI ON CACHE BOOL "Set by default for CUDA PR testing")
set (Kokkos_ENABLE_CUDA ON CACHE BOOL "Set by default for CUDA PR testing")
set (KOKKOS_ARCH Power8,Pascal60 CACHE STRING "Set by default for CUDA PR testing")
set (Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE OFF CACHE BOOL "Set by default for CUDA PR testing")
set (Sacado_ENABLE_HIERARCHICAL_DFAD ON CACHE BOOL "Set by default for CUDA PR testing")
set (Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA ON CACHE BOOL "Set by default for CUDA PR testing")
set (Kokkos_ENABLE_CUDA_LAMBDA ON CACHE BOOL "Set by default for CUDA PR testing")
set (Phalanx_KOKKOS_DEVICE_TYPE CUDA CACHE STRING "Set by default for CUDA PR testing")
set (MPI_EXEC_POST_NUMPROCS_FLAGS "-map-by;socket:PE=4" CACHE STRING "Set by default for CUDA PR testing")

# Options set to match the ATDM build
set (Trilinos_ENABLE_DEBUG OFF CACHE BOOL "Set by default for CUDA PR testing")
set (Trilinos_ENABLE_DEBUG_SYMBOLS OFF CACHE BOOL "Set by default for CUDA PR testing")
set (BUILD_SHARED_LIBS OFF CACHE BOOL "Set by default for CUDA PR testing")
set (Tpetra_INST_SERIAL ON CACHE BOOL "Set by default for CUDA PR testing")
set (Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF CACHE BOOL "Set by default for CUDA PR testing")
set (EpetraExt_ENABLE_HDF5 OFF CACHE BOOL "Set by default for CUDA PR testing")
set (Panzer_FADTYPE "Sacado::Fad::DFad<RealType>" CACHE STRING "Set by default for CUDA PR testing")
set (Kokkos_ENABLE_Debug_Bounds_Check ON CACHE BOOL "Set by default for CUDA PR testing")
set (KOKKOS_ENABLE_DEBUG ON CACHE BOOL "Set by default for CUDA PR testing")

# TPL settings specific to CUDA build
set (TPL_ENABLE_CUDA ON CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_CUSPARSE ON CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_Pthread OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_BinUtils OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_BLAS ON CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_BLAS_LIBRARIES "-L$ENV{BLAS_ROOT}/lib;-lblas;-lgfortran;-lgomp;-lm" CACHE STRING "Set by default for CUDA PR testing")
set (TPL_ENABLE_Boost ON CACHE BOOL "Set by default for CUDA PR testing")
set (Boost_INCLUDE_DIRS "$ENV{BOOST_ROOT}/include" CACHE FILEPATH "Set by default for CUDA PR testing")
set (TPL_Boost_LIBRARIES "$ENV{BOOST_ROOT}/lib/libboost_program_options.a;$ENV{BOOST_ROOT}/lib/libboost_system.a" CACHE FILEPATH  "Set by default for CUDA PR testing")
set (TPL_ENABLE_BoostLib ON CACHE BOOL "Set by default for CUDA PR testing")
set (BoostLib_INCLUDE_DIRS "$ENV{BOOST_ROOT}/include" CACHE FILEPATH "Set by default for CUDA PR testing")
set (TPL_BoostLib_LIBRARIES "$ENV{BOOST_ROOT}/lib/libboost_program_options.a;$ENV{BOOST_ROOT}/lib/libboost_system.a" CACHE FILEPATH "Set by default for CUDA PR testing")
set (TPL_ENABLE_METIS OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_ParMETIS OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_Scotch OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_HWLOC OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_LAPACK ON CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_LAPACK_LIBRARIES "-L$ENV{LAPACK_ROOT}/lib;-llapack;-lgfortran;-lgomp" CACHE STRING "Set by default for CUDA PR testing")
set (TPL_ENABLE_Zlib OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_CGNS OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_HDF5 ON CACHE BOOL "Set by default for CUDA PR testing")
set (HDF5_INCLUDE_DIRS "$ENV{HDF5_ROOT}/include" CACHE FILEPATH "Set by default for CUDA PR testing")
set (TPL_HDF5_LIBRARIES "-L$ENV{HDF5_ROOT}/lib;$ENV{HDF5_ROOT}/lib/libhdf5_hl.a;$ENV{HDF5_ROOT}/lib/libhdf5.a;-lz;-ldl" CACHE FILEPATH "Set by default for CUDA PR testing")
set (TPL_ENABLE_Netcdf ON CACHE BOOL "Set by default for CUDA PR testing")
set (Netcdf_INCLUDE_DIRS "$ENV{NETCDF_ROOT}/include" CACHE FILEPATH "Set by default for CUDA PR testing")
IF ("$ENV{PNETCDF_ROOT}" STREQUAL "")
  SET(PNETCDF_ROOT "$ENV{NETCDF_ROOT}")
ELSE()
  SET(PNETCDF_ROOT "$ENV{PNETCDF_ROOT}")
ENDIF()
set (TPL_Netcdf_LIBRARIES "-L$ENV{NETCDF_ROOT}/lib;$ENV{NETCDF_ROOT}/lib/libnetcdf.a;${PNETCDF_ROOT}/lib/libpnetcdf.a;${TPL_HDF5_LIBRARIES}" CACHE STRING "Set by default for CUDA PR testing")
# SuperLU and SuperLUDist is available on ride and could be enabled for the CUDA PR build
set (TPL_ENABLE_SuperLU OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_SuperLUDist OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_BoostLib OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_ENABLE_Matio OFF CACHE BOOL "Set by default for CUDA PR testing")
set (TPL_DLlib_LIBRARIES "-ldl" CACHE FILEPATH "Set by default for CUDA PR testing")

# The compile times for two Panzer files went up to over 6 hours. This
# turns off one feature that allows these in about 24 minutes. Please remove
# when issue #7532 is resolved.
set (Sacado_NEW_FAD_DESIGN_IS_DEFAULT OFF CACHE BOOL "Temporary fix for issue #7532" )

# Disable some packages that can't be tested with this PR build
set (Trilinos_ENABLE_ShyLU_NodeTacho OFF CACHE BOOL
  "Can't test Tacho with CUDA without RDC" FORCE)

# Force some tests to run in serial in this PR build (usually to resolve random timeouts that can occur under contention)
set (Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1_SET_RUN_SERIAL ON CACHE BOOL "Run serial for CUDA PR testing")

# Options used to clean up build
set (MueLu_ParameterListInterpreterTpetra_MPI_1_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (MueLu_ParameterListInterpreterTpetraHeavy_MPI_1_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (STKUnit_tests_stk_ngp_test_utest_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_adv-diff-react_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_adv-diff-react_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_poisson_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_03_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_navier-stokes_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_navier-stokes_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_nonlinear-elliptic_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_nonlinear-elliptic_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_obstacle_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_topo-opt_poisson_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_test_elementwise_TpetraMultiVector_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_NonlinearProblemTest_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (TrilinosCouplings_Example_Maxwell_MueLu_MPI_1_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (TrilinosCouplings_Example_Maxwell_MueLu_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")

# Disable some tests that should not need to be disabled but do because the
# Trilinos PR tester is using too high a parallel level for ctest. (If the
# ctest parallel test level is dropped from 29 to 8, all of these will pass.)
set (MueLu_UnitTestsIntrepid2Tpetra_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerAdaptersSTK_PoissonInterfaceExample_3d_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_poisson-boltzmann_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")

# Disable a couple of unit tests in test KokkosCore_UnitTest_Cuda_MPI_1 that
# are randomly failing in PR test iterations (#6799)
set (KokkosCore_UnitTest_Cuda_MPI_1_EXTRA_ARGS
  "--gtest_filter=-cuda.debug_pin_um_to_host:cuda.debug_serial_execution"
  CACHE STRING "Temporary disable for CUDA PR testing")


# Disable a few failing tests for initial release of Cuda 10.1.105 PR build
set (EpetraExt_inout_test_LL_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (EpetraExt_inout_test_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (Teko_testdriver_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (Zoltan2_fix4785_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")


# UVM = OFF
set (Kokkos_ENABLE_CUDA_UVM OFF CACHE BOOL "Set by default for CUDA PR testing")
set (Tpetra_ENABLE_CUDA_UVM OFF CACHE BOOL "Set by default for CUDA PR testing")

# Turn off packages currently failing with UVM = OFF
set (Trilinos_ENABLE_Panzer OFF CACHE BOOL "Turn off packages for UVM build")
set (Trilinos_ENABLE_Stokhos OFF CACHE BOOL "Turn off packages for UVM build")
set (Trilinos_ENABLE_Intrepid2 OFF CACHE BOOL "Turn off packages for UVM build")
set (Trilinos_ENABLE_TrilinosCouplings OFF CACHE BOOL "Turn off packages for UVM build")

# Turn off tests currently failing with UVM = OFF
# Tpetra UVM = OFF tests
set (TpetraCore_CrsMatrix_PackUnpack_MPI_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_sumIntoStaticProfileExtraSpace_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue364_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockView_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_PackUnpack_MPI_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnitTests_Swap_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnpackMerge_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_UnitTests_Swap_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug6171_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_SubmapImportTests_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug5978_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_insertGlobalIndicesFiltered_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_SubmapExportTests_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ReverseCommunication_Issue227_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue1752_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_ExportTest_Bug5882_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_UnpackMerge_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug6069_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlankRowBugTest_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnitTests4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_UnpackLongRows_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnitTests3_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_UnitTests1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_RowMatrixTransposer_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue_3968_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnitTests2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_RowMatrixTransposer_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BugTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMAssembly_TotalElementLoopSP_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockCrsMatrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_ReplaceLocalValues_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_2DRandomDist_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_NonlocalAfterResume_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ImportExport2_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_EpetraRowMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_UnitTests0_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_ReplaceDiagonal_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_ReindexColumns_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson07_kokkos_fill_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ImportExport_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_LeftRightScale_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMarket_Operator_Test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_NonlocalSumInto_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_MultipleFillCompletes_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_ReplaceDomainMapAndImporter_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_TransformValues_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_NonlocalSumInto_Ignore_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Equilibration_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_GetRowCopy_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_gaussSeidel_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMultiVector_Fix3101_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMAssembly_InsertGlobalIndicesFESP_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Distributor_CreateFromSendsAndRecvs_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_ReindexColumns_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue_114_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Bug6288_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_AdditiveSchwarzHalo_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson05_redistribution_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Albany182_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMarket_Tpetra_CrsGraph_InOutTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_StaticImportExport_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FECrsMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_data_redist_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMarket_Tpetra_CrsMatrix_InOutTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_matrix_fill_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Directory_Issue6987_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ImportExport_ImportConstructExpert_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Import_Union_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_power_method_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_UnpackIntoStaticGraph_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson03_power_method_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_StaticImportExport_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsGraph_getNumDiags_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_transpose_sortedRows_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_iallreduce_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMultiVector_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_createDeepCopy_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockCrsPerfTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_rcb_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ExportToStaticGraphCrsMatrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_idot_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MV_reduce_strided_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue601_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug6069_1_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson06_custom_operator_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FECrsGraph_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FEMAssembly_TotalElementLoopSPKokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_WithGraph_Cuda_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Bug7758_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Bug7745_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug7745_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_RemoveEmptyProcesses_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_StaticView_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_SequentialTsqr_contiguousCacheBlocks_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_copyConvert_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MultiVector_MicroBenchmark_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_issue_434_not_yet_initialized_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_DistTsqr_1_proc_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_assembleElement_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue46_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_issue_434_already_initialized_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockMultiVector2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_deep_copy_SerialDenseMatrix_to_MultiVector_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_gemv_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Bug5800_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_user_initializes_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MultiVector_TwoArgRandomize_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug5378_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_getEntryOnHost_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MV_Kokkos_DualView_subview_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_createMirrorView_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockExpNamespace_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_tpetra_initializes_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue510_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_deep_copy_MultiVector_to_SerialDenseMatrix_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_tpetra_initializes_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_user_initializes_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_computeOffsetsFromConstantCount_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue510_Create2x_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_TsqrAdaptor_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_SequentialTsqr_noncontiguousCacheBlocks_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_does_not_double_initialize_Kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_copyOffsets_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_FixedHashTableTest_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MultiVector_get2dView_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_Combine_10000rows_11cols_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_idot_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_computeOffsetsFromCounts_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_initializes_Kokkos_inner_scope_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_Combine_100rows_5cols_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_CombineNodeTsqr_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_Combine_100rows_50cols_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug6051_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug5822_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_matrix_construct_heat2d_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug5822_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_OneToOne_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_matrix_construct_heat2d_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MV_subViewSomeZeroRows_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_ProblematicLookup_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CooMatrix_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_NegativeBaseIndexTest_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_getMyGlobalIndices_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_5000rows_100cols_Sequential_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_applyDirichlet_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_warn_on_post_finalize_destruction_issue_2372_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockMap_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_LocalMap_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_no_warn_on_pre_finalize_destruction_issue_2372_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_user_initializes_mpi_and_provides_comm_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ImportExport2_CrsSortingUtils_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue_607_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue_2198_no_more_than_4_processes_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_DetermineLocalTriangularStructure_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_WithLocalAccess_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug5399_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_TpetraUtils_crsUtils_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_isLocallyFitted_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_100rows_20cols_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_isOneToOne_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Directory_Issue7223_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_removeEmptyProcesses_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson02_init_map_vec_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMarket_Tpetra_Map_InOutTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Directory_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_Bug2431_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_provides_comm_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_getMinGlobalIndex_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_user_initializes_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_ForEach_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MatrixMarket_Tpetra_MultiVector_InOutTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson02_read_modify_vec_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_10000rows_20cols_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_aliased_deep_copy_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_initialize_where_tpetra_initializes_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Map_replaceCommWithSubset_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_map_contiguous_and_uniform_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_vector_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_map_cyclic_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Bug5474_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MultiVector_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson01_mpi_only_through_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_map_contiguous_no_global_num_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Issue1454_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_initializing_tpetra_with_teuchos_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_withLocalAccess_generic_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson02_read_modify_vec_no_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MakeOptColMap_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_Transform_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_lesson01_no_mpi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_initializing_tpetra_with_teuchos_serial_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_guide_map_contiguous_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_DistTsqr_4_proc_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_BlockMultiVector_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_100rows_5cols_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_10000rows_5cols_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_gemm_m_eq_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_gemm_m_eq_5_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_gemm_m_eq_13_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_gemm_m_eq_2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_WithGraph_Serial_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_CuSolver_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_CuSolverNodeTsqr_5000_20_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_CuSolverNodeTsqr_11_5_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_cudaAwareMpi_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_check_launch_blocking_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraTSQR_FullTsqr_Accuracy_1000rows_15cols_CuSolver_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_MultiVector_MixedNode_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_idot_no_cuda_aware_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_idot_no_cuda_aware_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TpetraCore_CrsMatrix_Bug8447_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Zoltan2 UVM = OFF tests
set (Zoltan2_coffeyMJ_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rectilinearRCB_left_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_glazeRCB_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rectilinearRCB_right_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_glaze2RCB_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_BasicCoordinateInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraVectorInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_OrderingAMD_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_random_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TaskMappingProblemTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_OneProc_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraMultiVectorInput_twoweights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraRowGraphInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_PartitioningTree_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraTraits_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Coloring1_simple_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_GraphModel2ndAdjsFromAdjs_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_GraphModel_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_simple_rectilinear_boxes_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mj_backwardcompat_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraRowMatrixInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraCrsGraphInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_kuberry_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_componentMetrics_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_OneProc_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_IdentifierModel_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_CoordinateModel_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_kokkosBlock_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Metric_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraCrsMatrixInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TaskMappingTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rcbTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraMultiVectorInput_noweights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_rcm_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_zoltanWithGraphAdapterVwgt_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTestPremigrate_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_OneProc_EWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_pamgenMeshAdapterTest_ghosthg_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_OneProc_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_coordinateDriverTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rcbDriverTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_ddirectoryTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_geometricVwgtTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_zoltanWithGraphAdapter_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_zoltanWithGraphAdapterEwgt_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_tpetraVecWithCopiesTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_simplePamgenTest_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Coloring1_commanchedual_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_geometricVwgt2Test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_EWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_chacoGraphMetricsTestNoGraph_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_OneProc_EWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_EWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_XpetraMultiVectorInput_oneweight_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_geometricTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Coloring1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_test578_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_chacoGraphMetricsTestNoGraphNoDistribute_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_Ashear_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_sorteddegree_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_chacoGraphMetricsTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_ParMETIS_OneProc_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Ordering1_natural_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_chacoGraphMetricsTestNoDistribute_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_multijaggedVwgt2Test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_OneProc_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_Galeri_VWeights_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_PolyPrec_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_Galeri_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_NormalizedLaplacian_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_GeneralizedLaplacian_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_uvmOff_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_ConstantsInitialGuess_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_PartialOrtho_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Sphynx_JacobiPrec_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_simple_sym_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_simple_nodistrib_sym_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_simple_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_simple_nodistrib_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_west0067_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_west0067_nodistrib_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_galeri1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_galeri2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_galeri2_sym_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TpetraCrsColorer_troublecauser_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TaskMappingTest3_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TimerManager_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_AllParameters_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Parameters_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_pamgenMeshAdapterTest_zoltanrcb_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_blockTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_AlltoAll_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_BasicVectorInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rcbPerformanceZ1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_BasicIdentifierInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_directoryTest_KokkosSimple_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_StridedData_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_PamgenMeshInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_rcb_C_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Environment_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Machine_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_fix2010_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_BasicKokkosIdentifierInput_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mj_int_coordinates_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Mapping_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_DebugManager_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_MetricOutputManager_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_nomjparts_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_PartitioningSolution_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_directoryTest_Kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_directoryTest_findUniqueGids.cpp_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_TPLTraits_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_nomjparts_odd_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_noholes_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_pamgenMeshAdapterTest_zoltanhg_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_findUniqueGids_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_pamgenMeshAdapterTest_mj_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_pamgenMeshAdapterTest_color_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_tpetraOneToOneMapTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjDriverTest_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_uvmOff_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_noholes_uvmOff_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_nomjparts_uvmOff_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_mjTest_geomgen_nomjparts_odd_uvmOff_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Zoltan2_Partitioning1_Quotient_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# MueLu UVM = OFF tests
set (MueLu_FixedMatrixPattern-Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ReuseSequenceTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_StandardReuse-Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsCreatePreconditionerTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_MatrixDriver_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsBlockedTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsTpetra_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Tpetra1DLaplace_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_CreateOperatorTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_BlockCrs-Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_SimpleTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ConvergenceTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_SimpleTpetraYaml_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_VarDofDriver_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_VarDofDriver_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsCreatePreconditionerTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsBlockedTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsTpetra_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ImportPerformance_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetraYaml_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetraSingleReduceCG_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetra_Distance2Coloring_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetra_WithGlobalConstants_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetraILU_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetraTripleMatrixProduct_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverTpetraIfpack2LinePartitioner_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_RAPScalingTestTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_SmootherScalingTestTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ReadMatrixTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_SmooVecCoalesce_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_CreateOperatorTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_BlockedTransfer_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ParameterListInterpreterTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Aggregation_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_tent_tent_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_sa_tent_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_tent_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_tent_line_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ConvergenceTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_sa_line_easy_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace2D_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace2D_Shift_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Line_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Interp_Laplace2D_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Elasticity3D_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Interp_SA_Laplace2D_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Tentative_Laplace2D_kokkos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace3D_SPARC_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace3D_SCP_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Maxwell3D-Tpetra_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Maxwell3D-Tpetra_0_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Stratimikos_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Redirection_Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_RAPScalingTestTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_SmootherScalingTestTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Stratimikos_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_ReadMatrixTpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace2D_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_tent_tent_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace2D_Shift_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_tent_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace3D_SCP_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_sa_tent_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Interp_Laplace2D_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Laplace3D_SPARC_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Line_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Interp_SA_Laplace2D_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Tentative_Laplace2D_kokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_sa_line_easy_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Driver_TogglePFactory_semi_tent_line_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_Structured_Elasticity3D_Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_DriverEnforceConstaints_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_LevelWrap-Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MueLu_UnitTestsIntrepid2Tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# ShyLU_DD UVM = OFF tests
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_IPOU_DIM3_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_GDSW_DIM2_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_GDSW_DIM3_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_RGDSW_DIM3_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_RGDSW_DIM2_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_one_rank_TLP_IPOU_DIM2_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDBDDC_bddc_standard_interface_test_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDBDDC_bddc_simple_interface_test_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB3_GDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB3_GDSW_DIM2_DPN1_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB3_GDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB3_GDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB2_GDSW_DIM2_DPN1_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB2_GDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_GDSW_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB2_GDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_RGDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_RGDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLBP_NB2_GDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSWStar_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_GDSWStar_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_GDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_GDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_GDSW_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSWStar_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSWStar_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_GDSWP_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_RGDSW_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_GDSWP_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_RGDSW_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSW_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_RGDSWP_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_RGDSWP_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_GDSWP_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_GDSWP_DIM2_DPN2_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_RGDSWP_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_RGDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_RGDSWP_DIM2_DPN2_ORD1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_GDSW_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Old_DIM2_DPN2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Matrix_DIM2_DPN2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Graph_DIM2_DPN2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Matrix_DIM2_DPN1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Graph_DIM2_DPN1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_overlap_Old_DIM2_DPN1_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsGraph_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_interfacepartitionofunity_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsMatrix_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_interfacesets_DIM2_CSOneToOne_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_GDSW_ML_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_GDSW_ML_DIM2_DPN1_ORD0_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_RGDSW_ML_DIM2_TPETRA_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_thyra_xpetra_elasticity_TLP_IPOUHarmonic_RGDSW_DIM2_TPETRA_DropCoupling_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDBDDC_bddc_sparse_solver_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ShyLU_DDFROSch_test_localpartitionofunitybasis_TPETRA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Ifpack2 UVM = OFF tests
set (Ifpack2_SolverFactory_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_MTGS_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_RILUKSingleProcessUnitTests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Jac_sm_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Diagonal_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_SGS_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ContainerFactory_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_small_gmres_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ILUT_5w_2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Jacobi_hb_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Issue234_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_small_pseudoblkcg_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Bordered_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Issue762_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_GS_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ILUT_5w_no_diag_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_MTSGS_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Jacobi_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ILUT_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Cheby_belos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_AdditiveSchwarzBug5963_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ILUT_hb_belos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Jacobi_hb_belos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_RILUK_hb_belos_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_AdditiveSchwarz_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_SGSMT_compare_with_Jacobi_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Tpetra_Native_GMRES_S_STEP_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_unit_tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_TomVankaTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_RILUK_hb_belos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_RBILUK_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_AdditiveSchwarz_RILUK_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_LocalSparseTriangularSolver2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ChebyshevConvergence_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_LocalSparseTriangularSolver_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Tpetra_Native_GMRES_SINGLE_REDUCE_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_MTSGS_belos_muelu_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_GS_belos_muelu_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_SGS_belos_muelu_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Tpetra_Native_GMRES_PIPELINE_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_MTGS_belos_muelu_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_Jacobi_belos_constGraph_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Ifpack2_ILUT_hb_belos_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Domi UVM = OFF tests
set (Domi_MDMap_UnitTests_1D_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_1_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_1_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_1D_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_1_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_1D_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_1_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_1_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_2_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_1_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_2_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_2_1_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_1D_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_1_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_2_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_1_2_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_2_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_2_1_1_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_1D_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_2_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_1_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_1_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_2D_4_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_2_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_2_1_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_1_4_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_2_2_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDMap_UnitTests_3D_4_1_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_1_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_1D_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_2_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_2D_4_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_4_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_1_4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_1_2_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_2_1_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_2_2_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Domi_MDVector_UnitTests_3D_4_1_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Kokkos UVM = OFF tests
set (KokkosAlgorithms_UnitTest_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosContainers_UnitTest_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_PushFinalizeHook_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_PushFinalizeHook_terminate_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Default_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_9_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_3_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_10_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_IncrementalTest_SERIAL_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_11_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_8_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_15_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_6_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_12_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_13_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_5_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_7_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_14_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_16_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_DefaultInit_4_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosContainers_UnitTest_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_IncrementalTest_CUDA_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosContainers_PerformanceTest_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_CudaInterOpStreams_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_CudaInterOpInit_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Serial1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Serial2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Develop_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Cuda1_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Cuda2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_Cuda3_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_ProfilingTestLibraryLoad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosCore_UnitTest_CudaTimingBased_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Belos UVM = OFF tests
set (Belos_Issue_3235_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_nonsymm_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_PseudoBlockCG_hb_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_BlockFGMRES_hb_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_PseudoBlockStochasticCG_hb_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_MVOPTester_complex_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_S_STEP_nonsymm_matrix_step5_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_MultipleSolves_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_BlockGMRES_hb_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_FixedPoint_tpetra_hb_test_left_precond_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_BlockCG_hb_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_HybridGMRES_hb_test_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_SolverFactory_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_PIPELINE_nonsymm_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_SINGLE_REDUCE_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_FixedPoint_tpetra_hb_test_right_precond_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_PIPELINE_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_S_STEP_nonsymm_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_S_STEP_nonsymm_matrix_step5_cholqr_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_SINGLE_REDUCE_nonsymm_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_OrthoManager_test_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_FixedPoint_tpetra_hb_test_no_precond_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_CG_SINGLE_REDUCE_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_CG_PIPELINE_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_S_STEP_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_GMRES_S_STEP_nonsymm_matrix_step5_cholqr2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_HybridGMRES_hb_test_0_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_OrthoManager_test_0_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_OrthoManager_benchmark_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_Native_CG_diagonal_matrix_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Belos_Tpetra_OrthoManager_test_2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Phalanx UVM = OFF tests
set (Phalanx_example_finite_element_assembly_mixed_field_types_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_tKokkosPerf_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_dag_manager_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_experimental_mdfield_refactor_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_assembly_slfad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_unmanaged_fields_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_assembly_dfad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_example_mesh_aux_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_evaluator_unit_tester_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_tKokkosAllocationTracker_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_mdfield_compiletime_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_aliased_fields_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_example_lof_aux_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_assembly_sfad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_example_finite_element_assembly_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_evaluator_macros_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_unmanaged_mdfields_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_memory_manager_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_field_tag_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_mdfield_runtime_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_field_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_tKokkos_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_mda_data_layout_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_mdfield_simulated_intrepid_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_example_workset_aux_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_view_allocation_size_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_performance_field_accessors_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_unmanaged_view_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_template_manager_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_dynamic_data_layout_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Phalanx_tKokkosNestedLambda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Sacado UVM = OFF tests
set (Sacado_view_example_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_NoViewSpec_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadFadKokkosTests_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_dfad_view_handle_example_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_Fad_Kokkos_CommTests_Serial_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_ViewFactoryTests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_Fad_Kokkos_CommTests_Cuda_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_Cuda_Hierarchical_SFad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_Cuda_Hierarchical_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_Cuda_Hierarchical_DFad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadFadKokkosTests_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosTests_NoViewSpec_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_NoViewSpec_Serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_NoViewSpec_Cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_Cuda_Hierarchical_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_Cuda_Hierarchical_SFad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Sacado_FadKokkosAtomicTests_Cuda_Hierarchical_DFad_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# STK UVM = OFF tests
set (STKSearch_STKSearch_unit_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKSearch_STKSearch_integration_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKDoc_tests_stk_io_doc_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_io_unit_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_STKSimd_Simd_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_topology_unit_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKDoc_tests_STKSimd_DocTest_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_mesh_unit_tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_util_parallel_UnitTest_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_STK_Balance_basic_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_tools_unit_tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKDoc_tests_stk_mesh_doc_tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_math_unit_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKDoc_tests_stk_topology_doc_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKDoc_tests_stk_util_doc_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_util_unit_tests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_STK_Transfer_how_to_use_copyTransfer_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (STKUnit_tests_stk_ngp_test_unit_tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Teko UVM = OFF tests
set (Teko_testdriver_tpetra_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_DiagnosticLinearOp_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_DiagonallyScaledPreconditioner_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_IterativePreconditionerFactory_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_InverseFactoryOperator_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_LU2x2InverseOp_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_ReorderBlocking_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_testdriver_tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_testdriver_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_RequestInterface_test_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_StratimikosFactory_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_ALOperator_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_ProbingFactory_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_UtilitiesTests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_DiagonalPreconditionerFactory_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_ExplicitOps_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_ModALPreconditioner_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Teko_StridedEpetraOperator_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Xpetra UVM = OFF tests
set (Xpetra_Laplace1D-Tpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MatrixMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_CrsMatrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_Matrix_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_Laplace1D-Xpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MultiVector_UnitTestsXpetraSpecific_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_StridedMapFactory_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_BlockedMultiVector_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_StridedMap_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MultiVector_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_Map_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_BlockedMultiVector_UnitTestsThyraSpecific_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_Map_UnitTests2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MultiVector_UnitTestsThyraSpecific_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_CrsMatrixUtils_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MapFactory_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Xpetra_MapExtractorFactory_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# ROL UVM = OFF tests
set (ROL_example_PDE-OPT_helmholtz_example_02_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_0ld_elasticity_example_01_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_0ld_elasticity_example_02_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_ginzburg-landau_example_02_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_ginzburg-landau_example_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_helmholtz_example_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_0ld_stoch-adv-diff_example_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_poisson_example_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_example_PDE-OPT_adv-diff-react_example_02_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_tpetra_test_function_TpetraBoundConstraintInterface_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_tpetra_test_vector_TpetraMultiVectorInterface_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_tpetra_test_vector_ScaledTpetraMultiVector_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_minitensor_test_sol_test_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_minitensor_test_function_test_02_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_minitensor_test_function_test_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ROL_adapters_minitensor_test_vector_test_01_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# KokkosKernels UVM = OFF tests
set (KokkosKernels_blas_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_sparse_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_graph_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_common_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_sparse_cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_graph_cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_blas_cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_common_cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_batched_dla_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_crsmatrix_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_spmv_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_spadd_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_spgemm_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_gauss_seidel_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_wiki_coloring_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (KokkosKernels_batched_dla_cuda_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Anasazi UVM = OFF tests
set (Anasazi_Tpetra_TraceMin_largest_standard_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_TraceMin_smallest_schur_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_TraceMin_smallest_proj_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_BlockKrylovSchur_Lap_test_0_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_BlockKrylovSchur_Lap_test_1_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_IRTR_Lap_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_BlockDavidson_Lap_test_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_Tpetra_MVOPTester_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Anasazi_MultiVecTraitsTest2_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Amesos2 UVM = OFF tests
set (Amesos2_GappedMtxGIDs-1proc_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_KLU2_Solver_Test_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_KLU2_UnitTests_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_SolverFactory_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_CrsMatrix_Adapter_Consistency_Tests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_Epetra_MultiVector_Adapter_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Amesos2_Epetra_RowMatrix_Adapter_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# NOX UVM = OFF tests
set (NOX_Tpetra_1DFEM_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_OperatorTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_1DFEM_ME_UnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_ConstraintModelEvaluator_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_HouseholderBorderedSolve_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_Heq_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_VectorOpsTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (NOX_Tpetra_MultiVectorOpsTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# SEACAS UVM = OFF tests
set (SEACASIoss_exodus_fpp_serialize_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (SEACASIoss_pamgen_exodus_io_info_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (SEACASIoss_create_path_fpp_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (SEACASIoss_exodus32_to_exodus64_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (SEACASIoss_exodus32_to_exodus32_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (SEACASIoss_exodus32_to_exodus32_pnetcdf_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Adelus UVM = OFF tests
set (Adelus_vector_random_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Adelus_vector_random_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Adelus_vector_random_MPI_3_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Adelus_vector_random_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Thyra UVM = OFF tests
set (ThyraTpetraAdapters_Simple2DTpetraModelEvaluatorUnitTests_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ThyraTpetraAdapters_TpetraThyraWrappersUnitTests_serial_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (ThyraTpetraAdapters_TpetraThyraWrappersUnitTests_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Teuchos UVM = OFF tests
set (TeuchosComm_stacked_timer_MPI_2_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TeuchosComm_stacked_timer4_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (TeuchosKokkosCompat_linkTest_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Piro UVM = OFF tests
set (Piro_AnalysisDriverTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (Piro_ThyraSolverTpetra_MPI_4_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# MiniTensor UVM = OFF tests
set (MiniTensor_test_Test_01_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
set (MiniTensor_test_Test_02_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")
# Stratimikos UVM = OFF tests
set (Stratimikos_test_single_amesos2_tpetra_solver_driver_KLU2_MPI_1_DISABLE ON CACHE BOOL "Turn off tests for UVM build")


include("${CMAKE_CURRENT_LIST_DIR}/PullRequestLinuxCommonTestingSettings.cmake")
