IF (SHOW_TEST_REQUIRED_PACKAGE_DEP)
  SET(TEST_REQUIRED_PACKAGES_ARGS  TEST_REQUIRED_PACKAGES  Triutils)
ENDIF()

IF (SHOW_TEST_REQUIRED_TPL_DEP)
  SET(TEST_REQUIRED_TPLS_ARGS  TEST_REQUIRED_TPLS  AMD)
ENDIF()

TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES Teuchos Epetra
  LIB_OPTIONAL_PACKAGES Triutils
  LIB_OPTIONAL_TPLS UMFPACK AMD PETSC
  ${TEST_REQUIRED_PACKAGES_ARGS}
  ${TEST_REQUIRED_TPLS_ARGS}
  )
