#
# Unset the ATDM_CONFIG_* env vars set by the get_system_info.sh script
#

unset ATDM_CONFIG_REAL_HOSTNAME
unset ATDM_CONFIG_CDASH_HOSTNAME
unset ATDM_CONFIG_SYSTEM_NAME
unset ATDM_CONFIG_SYSTEM_DIR
unset ATDM_CONFIG_CUSTOM_CONFIG_DIR
unset ATDM_CONFIG_KNOWN_HOSTNAME     # Deprecated!
unset ATDM_CONFIG_KNOWN_SYSTEM_NAME  # Deprecated!
