TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
    Classic classic  PS  REQUIRED
    Kernels kernels  PS  OPTIONAL
    TSQR    tsqr     PS  OPTIONAL
    Core    core     PS  REQUIRED
  )
