SET(POTENTIAL_BINDER_BIN "$ENV{BINDER_ROOT}/bin")

FIND_PROGRAM(BINDER_EXECUTABLE REQUIRED
  NAMES binder
  HINTS ${POTENTIAL_BINDER_BIN} ${BINDER_PATH}
)

message(STATUS "Found Binder executable: ${BINDER_EXECUTABLE}")
