
IF (TPL_ENABLE_MPI)
  TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( STRUMPACK
  REQUIRED_HEADERS "StrumpackSparseSolverMPIDist.hpp"
  REQUIRED_LIBS_NAMES "strumpack"
  )
ELSE (NOT TPL_ENABLE_MPI)
  TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( STRUMPACK
  REQUIRED_HEADERS "StrumpackSparseSolver.hpp"
  REQUIRED_LIBS_NAMES "strumpack"
  )
ENDIF(TPL_ENABLE_MPI)

IF (TPL_ENABLE_STRUMPACK)
  SET(CMAKE_REQUIRED_INCLUDES ${TPL_STRUMPACK_INCLUDE_DIRS})
  SET(CMAKE_REQUIRED_LIBRARIES ${TPL_STRUMPACK_LIBRARIES} ${TPL_ParMETIS_LIBRARIES} ${TPL_METIS_LIBRARIES} ${TPL_Scotch_LIBRARIES} ${TPL_BLAS_LIBRARIES} ${TPL_SCALAPACK_LIBRARIES} ${TPL_BLACS_LIBRARIES})
  SET(CMAKE_REQUIRED_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
ENDIF(TPL_ENABLE_STRUMPACK)
