INCLUDE(TPLDeclareLibraries)

IF(TPL_ENABLE_MPI)
  TPL_DECLARE_LIBRARIES( HDF5
    REQUIRED_HEADERS hdf5.h
    REQUIRED_LIBS_NAMES hdf5 z
    )
ELSE()
  TPL_DECLARE_LIBRARIES( HDF5
    REQUIRED_HEADERS hdf5.h
    REQUIRED_LIBS_NAMES hdf5
    )
ENDIF()
