
# Thrust TPL requires CUDA
IF (NOT TPL_ENABLE_CUDA)
  MESSAGE(FATAL_ERROR "\nThrust TPL requires that CUDA support is enabled. Please set \n  TPL_ENABLE_CUDA=ON\n\n")
ELSE()
  IF (NOT TPL_Thrust_INCLUDE_DIRS AND NOT CUDA_VERSION VERSION_LESS "4.0")
    #SET(TPL_Thrust_INCLUDE_DIRS ${TPL_CUDA_INCLUDE_DIRS} CACHE STRING "" FORCE)
    SET(TPL_Thrust_INCLUDE_DIRS ${TPL_CUDA_INCLUDE_DIRS})
  ENDIF()
  TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( Thrust
      REQUIRED_HEADERS thrust/for_each.h
  )
ENDIF()

