

IF (NOT KOKKOSKERNELS_HAS_TRILINOS AND NOT KOKKOSKERNELS_HAS_PARENT)

IF (DEFINED KokkosKernels_REQUIRE_DEVICES)
  STRING(REPLACE "," ";" REQUIRE_DEVICES "${KokkosKernels_REQUIRE_DEVICES}")
  KOKKOS_CHECK(DEVICES ${REQUIRE_DEVICES})
ENDIF()

IF (DEFINED KokkosKernels_REQUIRE_OPTIONS)
  STRING(REPLACE "," ";" REQUIRE_OPTIONS "${KokkosKernels_REQUIRE_OPTIONS}")
  KOKKOS_CHECK(OPTIONS ${REQUIRE_OPTIONS})
ENDIF()

IF (DEFINED KokkosKernels_REQUIRE_ARCH)
  STRING(REPLACE "," ";" REQUIRE_ARCH "${KokkosKernels_REQUIRE_ARCH}")
  KOKKOS_CHECK(ARCH ${REQUIRE_ARCH})
ENDIF()

IF (DEFINED KokkosKernels_REQUIRE_TPLS)
  STRING(REPLACE "," ";" REQUIRE_TPLS "${KokkosKernels_REQUIRE_TPLS}")
  KOKKOS_CHECK(TPLS ${REQUIRE_TPLS})
ENDIF()


ENDIF()

