SET(TPL_ENABLE_JDK     ON      CACHE BOOL "")
SET(TPL_ENABLE_OpenSSL ON      CACHE BOOL "")
SET(TPL_ENABLE_LIBXML2 ON      CACHE BOOL "")
SET(TPL_ENABLE_HDF5CPP ON      CACHE BOOL "")
SET(TPL_ENABLE_Zlib    ON      CACHE BOOL "")
SET(TPL_ENABLE_PVM     ON      CACHE BOOL "")
SET(TPL_ENABLE_TCL     ON      CACHE BOOL "")
SET(TPL_ENABLE_Netcdf ON CACHE BOOL "")

SET(ANT_PATH         /usr/bin                                                     CACHE FILEPATH "")
SET(TCLSH_PATH       /usr/bin                                                     CACHE FILEPATH "")
SET(TCL_LIBRARY_NAMES "tcl8.5"                                                    CACHE STRING   "")
SET(JDK_INCLUDE_DIRS "/usr/lib/jvm/java/include;/usr/lib/jvm/java/include/linux"  CACHE FILEPATH "")
SET(JDK_LIBRARY_DIRS /usr/lib/jvm/java/jre/lib/amd64/server                       CACHE FILEPATH "")
SET(PVM_LIBRARY_DIRS /opt/intel-11.1.064/tpls/pvm3/lib/LINUX64                    CACHE FILEPATH "")
SET(PVM_INCLUDE_DIRS /opt/intel-11.1.064/tpls/pvm3/include                        CACHE FILEPATH "")
SET(Netcdf_LIBRARY_DIRS /opt/gcc-4.5.1/tpls/netcdf-4.1.1/lib CACHE FILEPATH "")
SET(Netcdf_INCLUDE_DIRS /opt/gcc-4.5.1/tpls/netcdf-4.1.1/include CACHE FILEPATH "")
