#
# Build all Secondary Stable CASL VRI add-on Trilnos packages with GCC 4.5.1 compiler
#

INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.pu241.gcc.4.5.1.cmake")
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/SubmitToCaslDev.cmake")

SET(COMM_TYPE MPI)
SET(BUILD_TYPE DEBUG)
SET(BUILD_DIR_NAME MPI_DEBUG_GCC_CASLDEV)
SET(CTEST_TEST_TYPE Experimental)
#SET(CTEST_TEST_TIMEOUT 900)
SET(Trilinos_ENABLE_SECONDARY_STABLE_CODE ON)
SET(Trilinos_PACKAGES LIME)
SET(Trilinos_EXTRAREPOS_FILE "${CTEST_SCRIPT_DIRECTORY}/ExtraExternalRepositories.casl_vri.cmake")
SET(EXTRA_CONFIGURE_OPTIONS
  )

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
