#
# Build all Secondary Stable Trilinos packages in core Trilinos with Intel 12.0.4 compiler
#

INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.pu241.icpc.12.0.4.cmake")
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/SubmitToTrilinos.cmake")

SET(COMM_TYPE SERIAL)
SET(BUILD_TYPE DEBUG)
SET(BUILD_DIR_NAME SERIAL_DEBUG_ICPC_TRILINOS)
SET(CTEST_TEST_TYPE Nightly)
#SET(CTEST_TEST_TIMEOUT 900)
SET(EXTRA_CONFIGURE_OPTIONS
  ${EXTRA_CONFIGURE_OPTIONS}
  -DTeuchos_ENABLE_STACKTRACE:BOOL=ON
  -DTrilinos_ENABLE_DEBUG:BOOL=ON
  -DSTK_ENABLE_BoostLib:BOOL=OFF
  )

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
