INCLUDE(${TRILINOS_HOME_DIR}/cmake/ctest/drivers/pu241/gcc-4.5.1-base-options.cmake OPTIONAL)
INCLUDE(${CTEST_SCRIPT_DIRECTORY}/gcc-4.5.1-base-options.cmake OPTIONAL)
SET(MPI_BASE_DIR "${TRILINOS_TOOLSET_BASE}" CACHE PATH "")
