# Must source /opt/casldev/env/casl_dev_env.sh before using this.
SET(CMAKE_SKIP_RPATH ON BOOL "")
#SET(BUILD_SHARED_LIBS ON CACHE BOOL "")
SET(TPL_ENABLE_Boost ON CACHE BOOL "")
SET(Boost_INCLUDE_DIRS /opt/tpls_src/boost_1_46_1 CACHE FILEPATH "")
SET(TPL_ENABLE_BinUtils ON CACHE BOOL "")
SET(CMAKE_C_COMPILER /opt/intel/Compiler/11.1/064/bin/intel64/icc CACHE FILEPATH "")
SET(CMAKE_CXX_COMPILER /opt/intel/Compiler/11.1/064/bin/intel64/icpc CACHE FILEPATH "")
SET(CMAKE_Fortran_COMPILER /opt/intel/Compiler/11.1/064/bin/intel64/ifort CACHE FILEPATH "")
SET(BLAS_LIBRARY_NAMES "mkl_intel_lp64;mkl_blas95_lp64;mkl_core;mkl_sequential" CACHE STRING "")
SET(BLAS_LIBRARY_DIRS "$ENV{MKLROOT}/lib/em64t" CACHE STRING "")
SET(LAPACK_LIBRARY_NAMES "mkl_lapack95_lp64" CACHE STRING "")
SET(LAPACK_LIBRARY_DIRS "$ENV{MKLROOT}/lib/em64t" CACHE FILEPATH "")
