SET(INTEL_11064_ROOT /opt/intel/Compiler/11.1/064)

SET(MKLROOT ${INTEL_11064_ROOT}/mkl)

SET(BLAS_LIBRARY_NAMES "mkl_intel_lp64;mkl_blas95_lp64;mkl_core;mkl_sequential" CACHE STRING "")
SET(BLAS_LIBRARY_DIRS "${MKLROOT}/lib/em64t" CACHE STRING "")
SET(LAPACK_LIBRARY_NAMES "mkl_lapack95_lp64" CACHE STRING "")
SET(LAPACK_LIBRARY_DIRS "${MKLROOT}/lib/em64t" CACHE FILEPATH "")
