
SET(INTEL_11_1_064_ROOT /opt/intel/Compiler/11.1/064)
SET(TBBROOT ${INTEL_11_1_064_ROOT}/tbb)

SET(TBB_INCLUDE_DIRS  ${TBBROOT}/include      CACHE FILEPATH "")
SET(TBB_LIBRARY_DIRS  ${TBBROOT}/lib/intel64  CACHE FILEPATH "")
