#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line and
# rename the file to "post-receive".
#. /opt/local/share/doc/git-core/contrib/hooks/post-receive-email

#export PATH=/usr/local/Python/2.5.1/bin:$PATH
#export PYTHONPATH=/data0/sierra/trac/lib:/data0/sierra/trac/lib/python2.5/site-packages:/data0/sierra/lib/svn-python:/data0/sierra/lib:/data0/sierra/lib/python2.5:/data0/sierra/lib/python2.5/site-packages:$PYTHONPATH
#export LD_LIBRARY_PATH=/data0/sierra/lib:$LD_LIBRARY_PATH

push_date=$(date -u "+%Y-%m-%d_%H:%M:%S-UTC")
while read oldrev newrev refname
do
    echo $oldrev $newrev $refname | hooks/post-receive-email
    #echo $oldrev $newrev $refname $push_date | hooks/post-receive-pushlog
    #echo $oldrev $newrev $refname | hooks/post-receive-trac
    #echo $oldrev $newrev $refname | hooks/post-receive-sourceforge
done

