#!/bin/sh
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master

pushdate=$(date -u "+%Y-%m-%d_%H:%M:%S-UTC")
while read oldrev newrev refname
do
    echo $oldrev $newrev $refname | hooks/post-receive-email
    test -x hooks/update_push_log.py && ./hooks/update_push_log.py \
      $oldrev $newrev $refname $pushdate
done
