SET(PROJECT_NAME Trilinos)

SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE_DEFAULT  OFF)

SET(${PROJECT_NAME}_GENERATE_REPO_VERSION_FILE_DEFAULT  ON)

SET(${PROJECT_NAME}_GENERATE_VERSION_DATE_FILES_DEFAULT ON)

SET(${PROJECT_NAME}_CTEST_DO_ALL_AT_ONCE_DEFAULT ON)

IF ( WIN32 AND NOT CYGWIN )
  MESSAGE(STATUS "Warning: Setting ${PROJECT_NAME}_ENABLE_Fortran=OFF by default"
   " because this is Windows (not cygwin) and we assume to not have Fortran!")
  SET(${PROJECT_NAME}_ENABLE_Fortran_DEFAULT OFF)
ELSE()
  SET(${PROJECT_NAME}_ENABLE_Fortran_DEFAULT ON)
ENDIF()
