TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
 SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
    SharedOnly  shared_only  PT  OPTIONAL
    StaticOnly  static_only  PT  OPTIONAL
    StaticExec  static_exec  PT  OPTIONAL
 )
