
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.sems.cmake")

#
# Set the options specific to this build case
#

SET(COMM_TYPE MPI)
SET(BUILD_TYPE DEBUG)
SET(BUILD_DIR_NAME ROL_MPI_DEBUG)
#SET(CTEST_TEST_TIMEOUT 900)

SET(Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF)

SET(Trilinos_ENABLE_CONFIGURE_TIMING ON)

SET(Trilinos_BRANCH develop)

SET(CTEST_TEST_TYPE Specialized)

SET( EXTRA_CONFIGURE_OPTIONS
 "-DCMAKE_BUILD_TYPE:STRING=DEBUG"
)

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
