
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.sems.cmake")

#
# Set the options specific to this build case
#

SET(COMM_TYPE MPI)
SET(BUILD_TYPE RELEASE)
SET(BUILD_DIR_NAME ROL_MPI_RELEASE)
#SET(CTEST_TEST_TIMEOUT 900)

SET(COMPILER_VERSION "Intel-17.0.1")

SET(Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF)

SET(Trilinos_ENABLE_CONFIGURE_TIMING ON)

SET(Trilinos_BRANCH develop)

SET(CTEST_TEST_TYPE Specialized)

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
