
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.sems.cmake")

#
# Set the options specific to this build case
#

SET(COMM_TYPE MPI)
SET(BUILD_TYPE RELEASE)
SET(BUILD_DIR_NAME ROL_DOWNSTREAM_MPI_RELEASE)
#SET(CTEST_TEST_TIMEOUT 900)

SET(Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF)

SET(Trilinos_ENABLE_CONFIGURE_TIMING ON)

SET(Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES TRUE)

SET(Trilinos_BRANCH develop)

SET(CTEST_TEST_TYPE Specialized)

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
