SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
  Core  core  PS  REQUIRED
  ParameterList parameterlist PS REQUIRED
  Comm  comm  PS  REQUIRED
  Numerics numerics PS REQUIRED
  Remainder remainder PS REQUIRED
  )

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS Eigen)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
