INCLUDE(TribitsCMakePolicies)
INCLUDE(Split)


#
# Read in the <build>/Testing/TAG file contents
#
#
FUNCTION(TRIBITS_READ_CTEST_TAG_FILE  TAG_FILE_IN  BUILD_START_TIME_OUT  CDASH_TRACK_OUT)
  FILE(READ "${TAG_FILE_IN}" TAG_FILE_STR)
  SPLIT("${TAG_FILE_STR}" "\n" TAG_FILE_STR_LIST)
  LIST(GET TAG_FILE_STR_LIST 0 BUILD_START_TIME)
  LIST(GET TAG_FILE_STR_LIST 1 CDASH_TRACK)
  SET(${BUILD_START_TIME_OUT} "${BUILD_START_TIME}" PARENT_SCOPE)
  SET(${CDASH_TRACK_OUT} "${CDASH_TRACK}" PARENT_SCOPE)
ENDFUNCTION()
