if(${CMAKE_PROJECT_NAME} STREQUAL "SEACAS")
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_PACKAGES Suplib Exodus
  )
else()
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_PACKAGES SEACASSuplib SEACASExodus
  )
endif()

