
MACRO(PyTrilinos2_MAKE_MPI_TEST TEST_NAME)

  TRIBITS_ADD_TEST(
    ${Python3_EXECUTABLE}
    NOEXEPREFIX
    NOEXESUFFIX
    NAME ${TEST_NAME}
    ARGS "${TEST_NAME}.py"
    PASS_REGULAR_EXPRESSION "OK"
    ENVIRONMENT "PYTHONPATH=${PyTrilinos2_PYTHONPATH}:$ENV{PYTHONPATH}"
    ${ARGN}
    )

  TRIBITS_COPY_FILES_TO_BINARY_DIR(${TEST_NAME}_cp
    SOURCE_FILES ${TEST_NAME}.py
    CATEGORIES BASIC)

ENDMACRO(PyTrilinos2_MAKE_MPI_TEST TEST_NAME)
