
MACRO(PyTrilinos2_MAKE_MPI_TEST TEST_NAME)

  FILE(COPY ${CMAKE_CURRENT_SOURCE_DIR}/${TEST_NAME}.py DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

  TRIBITS_ADD_TEST(
    ${PYTHON_EXECUTABLE}
    NOEXEPREFIX
    NOEXESUFFIX
    NAME ${TEST_NAME}
    ARGS "${TEST_NAME}.py"
    PASS_REGULAR_EXPRESSION "OK"
    ENVIRONMENT "PYTHONPATH=${PyTrilinos2_PYTHONPATH}"
    ${ARGN}
    )

ENDMACRO(PyTrilinos2_MAKE_MPI_TEST TEST_NAME)
