SET(LIB_REQUIRED_DEP_PACKAGES Tpetra Teuchos Zoltan)
SET(LIB_OPTIONAL_DEP_PACKAGES ShyLU_NodeTacho)
SET(TEST_REQUIRED_DEP_PACKAGES Gtest)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS MPI METIS)
SET(LIB_OPTIONAL_DEP_TPLS MKL PARDISO_MKL SuperLU)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

