#include "RFGen_Shards.h"

namespace RFGen
{

SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION( Eigen )

SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION( Cell )

SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION( Point )

SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION( Dim )

}

