# Define these vars to see invalid usage checking and errors!
IF (SPKB_SHOW_SE_PKG_LIB_IMPORTEDLIBS_ERROR)
  SET(EXTRA_TAL_ARGS IMPORTEDLIBS pws_b)
ELSEIF (SPKB_SHOW_UPSTREAM_SE_PKG_LIB_IMPORTEDLIBS_ERROR)
  SET(EXTRA_TAL_ARGS IMPORTEDLIBS simplecxx)
ENDIF()
PRINT_NONEMPTY_VAR(EXTRA_TAL_ARGS)
