#!/bin/bash

#Set path to Trilinos:
TRILINOS_PATH=${HOME}/Trilinos

# You could load a devpack here, but for now assume it was loaded.
# module load devpack

# Set up backends for Trilinos
export CUDA=OFF
export OPENMP=ON
export PTHREAD=OFF
export SERIAL=OFF
export COMPLEX=OFF

# Set up Architecture

#Intel SandyBridge / IvyBridge
#export ARCH_FLAG="-mavx"
#Intel Haswell
export ARCH_CXX_FLAG="-xCORE-AVX2"
export ARCH_C_FLAG="-xCORE-AVX2"
export BLAS_LIBRARIES=${MKLROOT}/lib/mic/libmkl_core.a
export LAPACK_LIBRARIES=${BLAS_LIBRARIES}
#Intel KNL
#export ARCH_CXX_FLAG="-xMIC-AVX512"
#export ARCH_C_FLAG="-xMIC-AVX512"
#export BLAS_LIBRARIES=${MKLROOT}/lib/mic/libmkl_core.a
#export LAPACK_LIBRARIES=${BLAS_LIBRARIES}
#IBM Power8:
#export ARCH_FLAG="-mcpu=power8"
#IBM Power8 + NVIDIA K80
#export ARCH_CXX_FLAG="-mcpu=power8 -arch=sm_37"
#export ARCH_C_FLAG="-mcpu=power8"
#IBM Power8 + NVIDIA P100
#export ARCH_CXX_FLAG="-mcpu=power8 -arch=sm_60"
#export ARCH_C_FLAG="-mcpu=power8"


# Set up Tests/Examples

export TESTS=ON
export EXAMPLES=ON


# Set up number of OpenMP Threads:

export OMP_NUM_THREADS=8



###############################################
###############################################
# Don't change things below
###############################################
###############################################




export JENKINS_DO_CUDA=${CUDA}
export JENKINS_DO_OPENMP=${OPENMP}
export JENKINS_DO_PTHREAD=${PTHREAD}
export JENKINS_DO_SERIAL=${SERIAL}
export JENKINS_DO_COMPLEX=${COMPLEX}

export JENKINS_ARCH_CXX_FLAG=${ARCH_CXX_FLAG}
export JENKINS_ARCH_C_FLAG=${ARCH_C_FLAG}

export JENKINS_DO_TESTS=${TESTS}
export JENKINS_DO_EXAMPLES=${EXAMPLES}

source ${TRILINOS_PATH}/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins

