#!/bin/bash

#Set path to Trilinos:
TRILINOS_PATH=${HOME}/Trilinos

# You could load a devpack here, but for now assume it was loaded.
# module load devpack

# Set up backends for Trilinos
export CUDA=OFF
export OPENMP=ON
export PTHREAD=OFF
export SERIAL=OFF
export COMPLEX=OFF

# Set up Architecture

export ARCH_FLAG="-mavx"

# Set up Tests/Examples

export TESTS=ON
export EXAMPLES=ON


# Set up number of OpenMP Threads:

export OMP_NUM_THREADS=8



###############################################
###############################################
# Don't change things below
###############################################
###############################################




export JENKINS_DO_CUDA=${CUDA}
export JENKINS_DO_OPENMP=${OPENMP}
export JENKINS_DO_PTHREAD=${PTHREAD}
export JENKINS_DO_SERIAL=${SERIAL}
export JENKINS_DO_COMPLEX=${COMPLEX}

export JENKINS_ARCH_FLAG=${ARCH_FLAG}

export JENKINS_DO_TESTS=${TESTS}
export JENKINS_DO_EXAMPLES=${EXAMPLES}

source ${TRILINOS_PATH}/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins

