IF(TPL_ENABLE_GTest)
  set(MAYBE_GTEST_TPL GTest)
  set(MAYBE_GTEST_PACKAGE)
ELSE()
  set(MAYBE_GTEST_TPL)
  set(MAYBE_GTEST_PACKAGE Gtest)
ENDIF()

TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES TeuchosCore KokkosCore KokkosKernels Sacado
  TEST_REQUIRED_PACKAGES ${MAYBE_GTEST_PACKAGE}
  TEST_REQUIRED_TPLS ${MAYBE_GTEST_TPL}
  LIB_REQUIRED_TPLS Boost
  )
