SET(Teuchos_VERSION 11.13)
SET(Teuchos_MAJOR_VERSION 11)
SET(Teuchos_MAJOR_MINOR_VERSION 111300)
SET(Teuchos_VERSION_STRING "11.13 (Dev)")
SET(Teuchos_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
