set(BLA_VENDOR Apple)
find_package(BLAS REQUIRED)
kokkoskernels_create_imported_tpl(ACCELERATE INTERFACE LINK_LIBRARIES ${ACCELERATE_LIBRARIES} COMPILE_OPTIONS -DACCELERATE_NEW_LAPACK LINK_OPTIONS "-framework Accelerate")
