# Do we need to list KLU2 as a dependency?
#
# SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Tpetra KLU2)
SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Tpetra)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES Triutils)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS MPI SuperLU )
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
