TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_TPLS Netcdf
  LIB_OPTIONAL_TPLS Pthread HDF5 MPI
  LIB_OPTIONAL_DEP_TPLS Pthread HDF5 MPI
  TEST_REQUIRED_TPLS Netcdf
  TEST_OPTIONAL_TPLS Pthread
  TEST_OPTIONAL_DEP_TPLS Pthread
)

