###############################################################################
# <pkg> Makefile.target
# <user>
# <date>
# $Id: Makefile.test,v 1.3 2008/01/02 17:18:47 9te Exp $
###############################################################################
# Copyright (C) 2008 Oak Ridge National Laboratory, UT-Battelle, LLC.
###############################################################################
# General Makefile.target for <pkg>
###############################################################################

testdeps := ${PKG_DEPENDS} ${NEMESIS_TEST_DEPENDS} ${NEMESIS_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${NEMESIS_TEST_LIBS} ${NEMESIS_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := lib<spkg>_test${libsuffix}
thistestlib := -L. -l<spkg>_test
thistestlib_dep := <spkg>_test.o <start>

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of <pkg> Makefile.target
###############################################################################
