#!/bin/bash

filelist=`ls *_Config.h* *_config.h* VerifyFortran.h`

for file in $filelist; do
  ext="${file##*.}"
  name="${file%.*}"
  mv $file ${name}_fcs.${ext}
  echo '#include "TrilinosSierraConfig.h"' >  $file
  echo "#include \"${name}_fcs.${ext}\"" >> $file
  sed -i '/FC_FUNC/d' ${name}_fcs.${ext}
  sed -i '/F77_FUNC/d' ${name}_fcs.${ext}
  sed -i '/F77_BLAS_MANGLE/d' ${name}_fcs.${ext}
  sed -i '/FortranCInterface_/d' ${name}_fcs.${ext}
done

echo '#if ! (defined (__IBMCPP__) || defined(__IBMC__))' >>  Teuchos_config.h
echo '#else' >>  Teuchos_config.h
echo '# define HAVE_TEUCHOS_BLASFLOAT_DOUBLE_RETURN' >>  Teuchos_config.h
echo '# define HAVE_SLAPY2_PROBLEM' >>  Teuchos_config.h
echo '# define HAVE_SLAPY2_DOUBLE_RETURN' >>  Teuchos_config.h
echo '# define HAVE_FIXABLE_COMPLEX_BLAS_PROBLEM' >>  Teuchos_config.h
echo '#endif' >>  Teuchos_config.h
sed -i '/HAVE_TEUCHOS_BLASFLOAT_DOUBLE_RETURN/d' Teuchos_config_fcs.h
sed -i '/HAVE_SLAPY2_PROBLEM/d' Teuchos_config_fcs.h
sed -i '/HAVE_SLAPY2_DOUBLE_RETURN/d' Teuchos_config_fcs.h
sed -i '/HAVE_FIXABLE_COMPLEX_BLAS_PROBLEM/d' Teuchos_config_fcs.h


sed -i '/FINITE_VALUE_HAVE_GLOBAL_ISINF/d' NOX_Config_fcs.h
sed -i '/FINITE_VALUE_HAVE_STD_ISINF/d' NOX_Config_fcs.h
sed -i '/FINITE_VALUE_HAVE_GLOBAL_ISNAN/d' NOX_Config_fcs.h
sed -i '/FINITE_VALUE_HAVE_STD_ISNAN/d' NOX_Config_fcs.h
