#include "Panzer_ExplicitTemplateInstantiation.hpp"

#include "MiniEM_AuxiliaryEquationSet_DarcySchurComplement.hpp"
#include "MiniEM_AuxiliaryEquationSet_DarcySchurComplement_impl.hpp"

PANZER_INSTANTIATE_TEMPLATE_CLASS_ONE_T(mini_em::AuxiliaryEquationSet_DarcySchurComplement)
