#include "Panzer_ExplicitTemplateInstantiation.hpp"

#include "MiniEM_AuxiliaryEquationSet_SchurComplement.hpp"
#include "MiniEM_AuxiliaryEquationSet_SchurComplement_impl.hpp"

PANZER_INSTANTIATE_TEMPLATE_CLASS_ONE_T(mini_em::AuxiliaryEquationSet_SchurComplement)
