#include "Panzer_ExplicitTemplateInstantiation.hpp"

#include "MiniEM_AuxiliaryEquationSet_ProjectedDarcySchurComplement.hpp"
#include "MiniEM_AuxiliaryEquationSet_ProjectedDarcySchurComplement_impl.hpp"

PANZER_INSTANTIATE_TEMPLATE_CLASS_ONE_T(mini_em::AuxiliaryEquationSet_ProjectedDarcySchurComplement)
