#!/bin/bash
# these are needed for Jenkins to access the machine
yum -y install java-1.8.0-openjdk
mkdir /scratch
chmod 777 /scratch

# lapack and blas - use the static libraries
yum -y install lapack-static.x86_64
yum -y install blas-static.x86_64

# create user directories 
su - trilinos "echo trilinos dir"
su - prwolfe "echo prwolfe dir"
# and from somewhere else do `ssh-copy-id $THIS_IP`

# setup directory - used to rsync the SEMS tpl mount
mkdir /projects
mkdir /projects/sems

# and finally the modules for the sems mount
# this will not work until the initial rsync
yum -y install environment-modules.x86_64
echo "/projects/sems/modulefiles/projects #sems stuff" >> /usr/share/Modules/init/.modulespath

