SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
  SubpackageA   A   PS  REQUIRED
  SubpackageB   B   PS  REQUIRED
  SubpackageC   C   PS  REQUIRED
  )

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
