
#include "Panzer_Dimension.hpp"

namespace panzer {

  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(Dim)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(IP)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(BASIS)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(NODE)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(Point)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(Cell)
  SHARDS_ARRAY_DIM_TAG_SIMPLE_IMPLEMENTATION(Dummy)

}
