INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../TribitsExProjCTestDriver.cmake")

SET(COMM_TYPE SERIAL)
SET(BUILD_TYPE DEBUG)
SET(COMPILER_VERSION GCC)
SET(BUILD_DIR_NAME ${COMM_TYPE}_${BUILD_TYPE})

SET( EXTRA_CONFIGURE_OPTIONS
  "-DBUILD_SHARED_LIBS:BOOL=ON"
  "-DCMAKE_BUILD_TYPE=DEBUG"
  "-DCMAKE_C_COMPILER=gcc"
  "-DCMAKE_CXX_COMPILER=g++"
  "-DCMAKE_Fortran_COMPILER=gfortran"
  "-DTribitsExProj_ENABLE_Fortran=ON"
  "-DTribitsExProj_TRACE_ADD_TEST=ON"
  )

SET(CTEST_TEST_TYPE Continuous)

TRIBITSEXPROJ_CTEST_DRIVER()
