# Define these vars to see invalid usage checking and errors!
IF (SPKB_SHOW_UPSTREAM_DEPLIBS_ERROR)
  SET(EXTRA_TAL_ARGS DEPLIBS simplecxx)
ELSEIF (SPKB_SHOW_M_DEPLIBS_ERROR)
  SET(EXTRA_TAL_ARGS DEPLIBS m)
ELSEIF (SPKB_SHOW_NONTESTONLY_IMPORTEDLIBS_ERROR)
  SET(EXTRA_TAL_ARGS IMPORTEDLIBS simplecxx)
ENDIF()
PRINT_NONEMPTY_VAR(EXTRA_TAL_ARGS)
