SET(LIB_REQUIRED_DEP_PACKAGES Kokkos TrilinosSS Teuchos)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES Kokkos TrilinosSS Teuchos)
SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS MKL VTune Scotch METIS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS MKL Scotch METIS)
