#ifndef STK_STK_BALANCE_STK_BALANCE_INTERNAL_BALANCEDEFAULTS_HPP_
#define STK_STK_BALANCE_STK_BALANCE_INTERNAL_BALANCEDEFAULTS_HPP_


namespace stk {
namespace balance {

enum AppTypeDefaults {NO_DEFAULTS, SM_DEFAULTS, SD_DEFAULTS};

}}

#endif /* STK_STK_BALANCE_STK_BALANCE_INTERNAL_BALANCEDEFAULTS_HPP_ */
