#!/bin/bash

TRILINOS_PATH=/home/knmorri/Git_Trilinos/Trilinos
EXTRA_ARGS=$@

cmake \
          -D ForTrilinos_ENABLE_EXTENDED:BOOL=ON \
          -D ForTrilinos_ASSERTIONS:BOOL=ON \
          -D CMAKE_BUILD_TYPE:STRING=DEBUG \
          -D Trilinos_ENABLE_DEFAULT_PACKAGES:BOOL=OFF \
          -D Trilinos_ENABLE_Epetra:BOOL=ON \
          -D Trilinos_ENABLE_Teuchos:BOOL=ON \
          -D Trilinos_ENABLE_CTrilinos:BOOL=ON \
          -D Trilinos_ENABLE_ForTrilinos:BOOL=ON \
          -D Trilinos_ENABLE_TESTS:BOOL=ON \
          -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
          -D CTrilinos_ENABLE_TESTS:BOOL=OFF \
          -D CTrilinos_ENABLE_EXAMPLES:BOOL=OFF \
          -D ForTrilinos_ENABLE_TESTS:BOOL=ON \
          -D ForTrilinos_ENABLE_EXAMPLES:BOOL=ON \
          -D DART_TESTING_TIMEOUT:STRING=600 \
          -D TPL_ENABLE_MPI:BOOL=ON \
          -D MPI_BASE_DIR:PATH="/opt/local/mpi/mpich/xlf13/1.2.7p1"\
          -D MPI_BIN_DIR:PATH="/opt/local/mpi/mpich/xlf13/1.2.7p1/bin"\
          -D MPI_INCLUDE_PATH:PATH="/opt/local/mpi/mpich/xlf13/1.2.7p1/include" \
          -D MPI_USE_COMPILER_WRAPPERS:BOOL=ON \
          -D MPI_Fortran_COMPILER:FILEPATH="/opt/local/mpi/mpich/xlf13/1.2.7p1/bin/mpif90" \
          -D MPI_CXX_COMPILER:FILEPATH="/opt/local/mpi/mpich/xlf13/1.2.7p1/bin/mpicxx" \
          -D MPI_C_COMPILER:FILEPATH="/opt/local/mpi/mpich/xlf13/1.2.7p1/bin/mpicc" \
          -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
          -D Trilinos_VERBOSE_CONFIGURE:BOOL=FALSE \
          -D BLAS_LIBRARY_DIRS:FILEPATH="/home/knmorri/lapack-3.2.1" \
          -D BLAS_LIBRARY_NAMES:STRING="blas_AIX.a" \
          -D TPL_ENABLE_LAPACK:STRING=ON \
          -D TPL_BLAS_LIBRARIES:FILEPATH="/home/knmorri/lapack-3.2.1/blas_AIX.a;/opt/IBM/compilers/xlf13.1/usr/lib/libxlf90.a" \
          -D TPL_LAPACK_LIBRARIES:FILEPATH="/home/knmorri/lapack-3.2.1/lapack_AIX.a;/opt/IBM/compilers/xlf13.1/usr/lib/libxlf90.a" \
          -D LAPACK_LIBRARY_DIRS:FILEPATH="/home/knmorri/lapack-3.2.1" \
          -D LAPACK_LIBRARY_NAMES:STRING="lapack_AIX.a" \
          -D CMAKE_CXX_FLAGS:STRING="-qrtti=all" \
          -D CMAKE_Fortran_FLAGS:STRING="-qfixed=72 -qxlines" \
          -D CMAKE_INSTALL_PREFIX="/home/knmorri/Git_Trilinos/Trilinos-MPI-10.0" \
          ${EXTRA_ARGS} \
          ${TRILINOS_PATH}



