#!/bin/csh
../configure --host=powerpc-ibm-aix5.1.0.0 \
    --enable-mpi \
    --enable-referencey12m --enable-aztecoo-azlu \
    --with-ar="ar -X64 csrv" \
    --with-blas="-lessl -L/sierra/Release/lapack/3.0/lib/dbg_dp_ibm -lblas" \
    --with-lapack="-lessl -L/sierra/Release/lapack/3.0/lib/dbg_dp_ibm -llapack" \
    --with-mpi-incdir=/usr/lpp/ppe.poe/include \
    --with-mpi-libdir=/usr/lpp/ppe.poe/lib \
    --with-mpi-cxx=xlC --with-mpi-cc=xlc --with-mpi-f77=f77 \
    --enable-nox --enable-nox-epetra \
    --enable-prerelease --enable-epetraext --enable-loca \
    CXX="xlC -q64 -qlanglvl=redefmac" \
    CXXCPP="KCC -E" \
    CC="xlc -b64 -q64" \
    F77="f77 -b64 -q64" \
    --with-cxxflags="-g" \
    --with-fflags="-g" \
    --with-cflags="-g" \
    LDFLAGS=

#    --with-cppflags="-qlanglvl=redefmac" \
# -qlanglvl=redefmac -I../epetra/src -I../../epetra/src" \
