#!/bin/bash

#export LDFLAGS='-L~/lib'
#--with-ldflags="-Mipa=fast" \
#--with-ldflags="-lhwpc -lpapi -lm" \
#--with-lapack="-lacml -lm" \
#--with-blas="-lacml -lm" \
#--with-libs="-lacml -lm"

$HOME/Trilinos/$1/configure \
CC=cc \
CXX=CC \
CPP="CC -E" \
F77=f77 \
CFLAGS="-fastsse" \
CFLAGS="-fast -Mscalarsse" \
CXXFLAGS="-fastsse -Minline=levels:10 -DHAVE_MPI_CXX -DMPICH_IGNORE_CXX_SEEK" \
CXXFLAGS="-fastsse -Minline=levels:20 -DHAVE_MPI_CXX -DMPICH_IGNORE_CXX_SEEK" \
CXXFLAGS="-Mipa=fast -Minline=levels:20 -DHAVE_MPI_CXX -DMPICH_IGNORE_CXX_SEEK" \
CXXFLAGS="-fast -Mscalarsse -Minline=levels:10 -DHAVE_MPI_CXX -DMPICH_IGNORE_CXX_SEEK" \
FFLAGS="-fastsse" \
CPPFLAGS="" \
FLIBS='-lpgftnrtl -lnspgc -lpgc -lm' \
--prefix=${PWD} \
--host=x86_64-unknown-linux-gnu \
--enable-mpi \
--disable-default-packages \
--disable-tests \
--disable-examples \
--enable-teuchos \
--enable-epetra \
--enable-epetraext \
--enable-aztecoo \
--enable-triutils \
--enable-galeri \
--enable-ifpack \
--enable-amesos \
--enable-ml
