#!/bin/sh
../Trilinos/configure \
--with-install="/usr/bin/install -p" \
CXX=g++ \
CC=gcc \
F77=g77 \
CPPFLAGS="-D_DEBUG" \
CXXFLAGS="-g -O0 -pedantic -ansi -Wall" \
CFLAGS="-g -O0 -pedantic -ansi -Wall" \
FFLAGS="-g -O0" \
FLIBS="-lg2c" \
--with-ldflags="-L/usr/local/lib" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-complex --enable-teuchos-gmp \
LIBS="-L/usr/local/lib -lgmpxx -lgmp" \
--enable-thyra \
--enable-epetra --enable-epetra-thyra \
--prefix=$HOME/PROJECTS/Trilinos.thyra_start/install-dir/serial/debug

#--enable-teuchos-gmp --with-incdir="/usr/local/include" --with-ldflags="-lgmp -lgmpxx" \
# Note: TSFExtended is enabled to make sure I don't break Kevin's code
# Note: Sundance needs TSF enabled!
# Note: Can not use --with-cppflags etc. since these are used *before* the standard C++ flags (CPPFLAGS)!
# ToDo: Turn back on -ansi once makefile is fixed!
