#!/bin/bash

# This script just writes the Trilinos dependencies to the current directory
# This makes it easy to debug dependency tracking without having to 
# distrub the main dependency files.

EXTRA_ARGS=$@

cmake \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_PACKAGES_UNITTEST_OVERRIDE:BOOL=ON \
-D Trilinos_SHORTCIRCUIT_AFTER_DEPENDENCY_HANDLING:BOOL=ON \
-D Trilinos_DEPS_XML_OUTPUT_FILE:STRING=$PWD/TrilinosPackageDependencies.xml \
$EXTRA_ARGS \
../../../Trilinos

#-D Trilinos_DUMP_PACKAGE_DEPENDENCIES:BOOL=ON \
