#!/bin/bash

#
# Before running this do:
#
# module switch mpi mpi/mvapich-1.0.1_ofed_intel-10.1-f015-c015
# export PATH=/home/rabartl/install/bin:$PATH
#

EXTRA_ARGS=$@

TRILINOS_HOME=/gscratch1/rabartl/PROJECTS/Trilinos.base/Trilinos
INSTALL_DIR=/gscratch1/rabartl/PROJECTS/install/trilinos/for_eric_c
PARMETIS_DIR=/projects/charon/people/ptlin/Alegra/TPL/parmetis/3.1
SUPERLUDIST_DIR=/projects/charon/people/ptlin/Alegra/TPL/superludist/2.0
Y12_DIR=/projects/charon/people/ptlin/Alegra/TPL/y12m/1.0

# The cache is not working correctly so clean cache
rm CMakeCache.txt


cmake \
-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D CMAKE_CXX_COMPILER:FILEPATH="mpicxx" \
-D CMAKE_C_COMPILER:FILEPATH="mpicc" \
-D CMAKE_Fortran_COMPILER:FILEPATH="mpif77" \
-D CMAKE_CXX_FLAGS:FILEPATH="-O2 -DCODE_MP -DMPICH_SKIP_MPICXX -DNDEBUG -DHAVE_CONFIG_H -fPIC -diag-disable 597" \
-D CMAKE_C_FLAGS:FILEPATH="-O2 -DCODE_MP -DMPICH_SKIP_MPICXX -DNDEBUG -DHAVE_CONFIG_H -fPIC" \
-D CMAKE_Fortran_FLAGS:FILEPATH="-O2 -fPIC" \
-D CMAKE_EXE_LINKER_FLAGS:STRING=" -L/projects/global/x86_64/compilers/intel/intel-10.1-fce-015/libf" \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="-lifcore -lifport -limf -lcxaguard -lrt -lpthread -lirc -lsvml -lm" \
-D BLAS_LIBRARY_DIRS:FILEPATH="/projects/charon/Alegra/TPL/lapackblas/3.0-n1/lib/mvapich_opt_tlcc_intel" \
-D LAPACK_LIBRARY_DIRS:FILEPATH="/projects/charon/Alegra/TPL/lapackblas/3.0-n1/lib/mvapich_opt_tlcc_intel" \
-D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC_MAX_NUMPROCS:STRING=4 \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
$EXTRA-ARGS \
$TRILINOS_HOME
