#!/bin/sh
../configure \
--with-mpi-compilers \
CXXFLAGS="-O2" \
CFLAGS="-O2" \
FFLAGS="-O2" \
FLIBS="" \
--with-mpi-libs="-lmpich" \
--with-blas="-L/opt/intel/mkl61/lib/32 -lmkl_ia32 -lguide" \
--with-lapack="-L/opt/intel/mkl61/lib/32 -lmkl_lapack -lmkl_ia32 -lguide" \
--with-ldflags="-ldwarf" \
--disable-default-packages \
--enable-triutils \
--enable-epetra \
--enable-teuchos --enable-teuchos-complex \
--enable-tsfcore --enable-tsfcore-epetra \


#--with-blas=/home/rabartl/MoochoSalsa/Salsa_arch_fast/linux-mpich-x86/lib/libblas.a \
#--with-lapack=/home/rabartl/MoochoSalsa/Salsa_arch_fast/linux-mpich-x86/lib/liblapack.a \
#--prefix=/home/rabartl/MoochoSalsa/Salsa_arch_fast/linux-mpich-x86
#CXX=mpiCC \
#CC=mpicc \
#F77=mpif77 \

# May need this???
#--enable-mpi-compilers \
#--with-mpi-libs=/usr/local/mpich/lib/libmpich.a \
#--with-mpi-compilers \
#--disable-tests \
#--with-ldflags='-static' \
#--enable-mpi --with-mpi-compilers --with-mpi-libs=-lmpich \
