#!/bin/sh
#
# This is the script that I run on my Linux machine sahp6556 on the SICO LAN
#
# Note: You must use gmake, not make, when you build this code!
#
rm config.cache
../../../Trilinos/configure \
--cache-file=config.cache \
CXX="purify -always-use-cache-dir -cache-dir=$HOME/purify-cache g++" \
CC=gcc \
F77=g77 \
CPPFLAGS="-D_DEBUG" \
CXXFLAGS="-g" \
CFLAGS="-g" \
FFLAGS="-g" \
--with-mpi-incdir=/usr/local/mpi/mpich/1.2.5.2/gcc-3.2.2/include \
--with-mpi-libs="-L/usr/local/mpi/mpich/1.2.5.2/gcc-3.2.2/lib -lmpich -lpmpich" \
--with-incdirs="-I/sierra/Release/UMFPACK/4.1/UMFPACK/Include -I/sierra/Release/UMFPACK/4.1/AMD/Include -I/sierra/Release/SuperLU/2.0/SRC" \
--with-libs="-L/sierra/Release/UMFPACK/4.1/lib/dbg_dp_gnu3.2.2ip -lumfpack -lamd -L/sierra/Release/y12m/1.00/lib/dbg_dp_gnu3.2.2ip -L/sierra/Release/SuperLU/2.0/lib/dbg_dp_gnu3.2.2ip -lsuperludist -ly12m -lm" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-complex \
--enable-thyra \
--enable-epetra --enable-epetra-thyra
