#!/bin/sh

# ----------------------------------------------------------------------------
# Set the location of the compilers and libraries. On a simple out-of-the-box
# Linux system, COMPILER_ROOT will probably be someplace like /usr/local. 
# On Kevin's TTU machines, there are multiple compiler versions located
# in directories /usr/local/${COMPILER_VERSION}, e.g., /usr/local/gcc-4.3.2.
# If your system isn't organized this way, you can copy this script
# and modify as per your system.
#
GCC_VERSION=4.5.1
COMPILER_VERSION=gcc-${GCC_VERSION}
COMPILER_ROOT=/usr/local/${COMPILER_VERSION}
BIN_PATH=${COMPILER_ROOT}/bin
LIB_PATH=${COMPILER_ROOT}/lib
INC_PATH=${COMPILER_ROOT}/include
# Location of Python.h. Not needed unless you're building the
# python wrappers.
PYTHON_INC_PATH=/usr/local/gcc-4.4.2/include/python2.6

# ----------------------------------------------------------------------------
# Specify directories for the Trilinos source and Trilnos data, and for
# the installation of this build.

# Set the installation path
INSTALL_PREFIX=$PWD

# Set the path to the Trilinos source distribution
TRILINOS_SRC_DIR=${HOME}/Code/Trilinos

# Set the path to the Trilinos data files. Some of the Sundance tests require
# large mesh files stored in TrilinosData. If the TrilinosData directory
# cannot be found, these tests will be disabled.
TRILINOS_DATA_DIR=${HOME}/Code/TrilinosData

# The source command is a bash extension and isn't available on all
# versions of /bin/sh. Use the "dot" instead.
#source ${HOME}/Code/Trilinos/sampleScripts/krlong-linux-common
. ${HOME}/Code/Trilinos/sampleScripts/krlong-linux-common

exit 0


