#!/bin/sh
rm config.cache
../../Trilinos/configure \
--cache-file=config.cache \
--with-mpi-compilers \
--with-mpi-libs=-lmpich \
CPPFLAGS="-D_DEBUG -DCODE_MP" \
CFLAGS="-g -O0" \
CXXFLAGS="-g -O0" \
FFLAGS="-g -O0" \
--with-blas="-L/opt/intel/mkl/lib/32 -lmkl_ia32 -lguide" \
--with-lapack="-L/opt/intel/mkl/lib/32 -lmkl_lapack -L/opt/intel/mkl/lib/32 -lmkl_ia32" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-complex \
--enable-thyra \
--enable-epetra --enable-epetra-thyra

