#!/bin/bash

EXTRA_ARGS=$@

# 2009/01/23: rabartl: Script I used to get Trilinos to build with CMake for
# MPI on the SCICO LAN.

if [ "$TRILINOS_HOME" == "" ]; then
  export TRILINOS_HOME=/var/scratch/rabartl/PROJECTS/Sierra.new/Aria_Trilinos/code/Trilinos/dev
fi

cmake \
-D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_BASE_DIR:PATH=/home/sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit \
  -D MPI_EXEC_PRE_NUMPROCS_FLAGS:STRING="--all-local" \
-D MEMORYCHECK_COMMAND:FILEPATH=/usr/local/bin/valgrind \
-D DART_TESTING_TIMEOUT:STRING=600 \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
$EXTRA_ARGS \
${TRILINOS_HOME}
