#!/bin/bash

EXTRA_ARGS=$@

TRILINOS_SRC_DIR=../../Trilinos

cmake \
-D Trilinos_CONFIGURE_OPTIONS_FILE=$TRILINOS_SRC_DIR/sampleScripts/linux-brain-mpi-dbg-options.cmake \
-D DART_TESTING_TIMEOUT:STRING=60.0 \
-D CMAKE_INSTALL_PREFIX:PATH=$HOME/PROJECTS/install/gcc-4.1.2/trilinos/mpi/dbg \
$EXTRA_ARGS \
$TRILINOS_SRC_DIR

# -D Trilinos_EXTRA_REPOSITORIES:STRING="preCopyrightTrilinos;LIMEExt" \
