#! /bin/sh

EXTRA_ARGS=$@

/usr/local/bin/cmake \
    -D CMAKE_BUILD_TYPE:STRING=DEBUG \
    -D CMAKE_INSTALL_PREFIX:PATH=/Users/hudson \
    -D BUILD_SHARED_LIBS:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D MPI_BASE_DIR:PATH=/usr/local \
    -D MPI_EXEC:FILEPATH=/usr/local/bin/mpiexec \
    -D 'MPI_EXEC_PRE_NUMPROCS_FLAGS:STRING=--mca;oob_tcp_if_include;lo0' \
    -D PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python \
    -D SWIG_EXCECUTABLE:FILEPATH=/usr/local/bin/swig \
    -D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF \
    -D TPL_ENABLE_BoostLib:BOOL=ON \
    -D Trilinos_ENABLE_Fortran:BOOL=OFF \
    -D Trilinos_ENABLE_TESTS:BOOL=OFF \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_TriUtils:BOOL=ON \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Isorropia:BOOL=ON \
    -D Trilinos_ENABLE_Pliris:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Galeri:BOOL=ON \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_IFPACK:BOOL=ON \
    -D Trilinos_ENABLE_Komplex:BOOL=ON \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D NOX_ENABLE_LOCA:BOOL=ON \
    -D Trilinos_ENABLE_PyTrilinos:BOOL=ON \
    -D PyTrilinos_ENABLE_TESTS:BOOL=ON \
    -D PyTrilinos_ENABLE_EXAMPLES:BOOL=ON \
    -D PyTrilinos_INSTALL_PREFIX:PATH=/Users/hudson \
    $EXTRA_ARGS
