#!/bin/sh
module load compilers/pgi-6.0
rm config.cache
$HOME/PROJECTS/Trilinos.base/Trilinos/configure \
--cache-file=config.cache \
CXX=pgCC CC=pgcc F77=pgf77 \
CPPFLAGS="-tp k8-64 -lacml -lpgmp -lpgthread" \
--with-blas="-L/usr/pgi-6.0/linux86-64/6.0/lib -lacml -lpgmp -lpgthread" \
--with-lapack="-L/usr/pgi-6.0/linux86-64/6.0/lib -lacml" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-complex \
--enable-thyra \
--enable-epetra \
--enable-rythmos
