#!/bin/sh
../../Trilinos/configure \
CFLAGS="-O2 -64" \
FFLAGS="-O2 -64" \
CXXFLAGS="-O2 -64 -LANG:std  -LANG:ansi-for-init-scope=ON -ptused -DMPI_NO_CPPBIND"  \
LDFLAGS=" -64 -L/usr/lib64/mips4/r10000 -L/usr/lib64/mips4 -L/usr/lib64 -LANG:std" \
--with-libs="/scratch1/mnpheno/Trilinos3PL/prebuilt/dscpack-1.0/dsclibdbl_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/umfpack-4.1/libumfpack_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/umfpack-4.1/libamd_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/mumps-4.3/libmumps_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/mumps-4.3/libpord_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/scalapack-1.7/libscalapack_atlantis.a /scratch1/mnpheno/Trilinos3PL/prebuilt/mumps-4.3/libblacs_atlantis.a -lfortran -lmpi" \
--with-incdirs="-I/scratch1/mnpheno/Trilinos3PL/prebuilt/dscpack-1.0 -I/scratch1/mnpheno/Trilinos3PL/prebuilt/umfpack-4.1 -I/scratch1/mnpheno/Trilinos3PL/prebuilt/mumps-4.3" \
--with-gnumake \
--disable-default-packages \
--enable-teuchos --enable-teuchos-complex --enable-teuchos-extended \
--enable-thyra \
--enable-epetra \
--enable-rythmos
