#!/bin/sh

../../../Trilinos/configure \
--with-install="/usr/sbin/install -p" \
--enable-export-makefiles \
--with-gnumake \
CPPFLAGS="-D_DEBUG" \
CXXFLAGS="-g -pto" \
CFLAGS="-g" \
FFLAGS="-g" \
LDFLAGS="-L/usr/local/lib -xlic_lib=sunperf" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-complex \
--enable-thyra \
--enable-epetra --enable-epetra-thyra \
--prefix=/home/rabartl/PROJECTS/install-dir/sun/serial/debug

# Note: Can not use --with-cppflags etc. since these are used *before* the standard C++ flags (CPPFLAGS)!


















