#!/bin/sh
../configure \
--with-ar="/home/rabartl/PROJECTS/Trilinos.base/Trilinos/sampleScripts/stratus_ar.pl ar cru" \
TRILINOS_TEMPLATE_OBJS="cxx_repository" \
CPPFLAGS="-DMPI_NO_CPPBIND -D__USE_STD_IOSTREAM" \
CXXFLAGS="-O2 " \
--disable-default-packages \
--disable-ml \
--enable-triutils \
--enable-epetra \
--enable-aztecoo \
--enable-ifpack \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-complex \
--enable-tsfcore --enable-tsfcore-epetra -enable-tsfcore-aztecoo \

#--enable-tsfextended : 2004/10/29: TSFExtended does not currently build on stratus
# --disable-aztecoo
