#!/bin/sh

##################################################################
# Configuration of Trilinos for use with the development version 
# of Sundance.
#
# This will NOT work with the old version of Sundance
##################################################################


BUILD_DIR=`pwd`

../configure --enable-mpi --with-mpi-libs="-lmpich -lpmpich" \
CXXFLAGS="-O3 -finline-functions -funroll-all-loops" \
--enable-tsfextended \
--enable-tsfcore \
--enable-tsfcore-epetra \
--enable-tsfcore-mpi \
--enable-tsfcore-aztecoo \
--enable-teuchos \
--enable-expat \
--disable-ml \
--enable-teuchos-extended \
--disable-new-package \
--disable-ml-examples \
--enable-nox \
--enable-nox-tsf \
--enable-nox-tsf-examples \
--disable-loca \
--with-install="/usr/bin/install -c -p" \
--prefix=$BUILD_DIR


