#!/bin/sh

##################################################################
# Configuration of Trilinos for use with the development version 
# of Sundance.
#
# This will NOT work with the old version of Sundance
##################################################################


BUILD_DIR=`pwd`

MKL_PATH=/opt/intel/mkl/lib/32

../configure CXXFLAGS="-O3 -tpp7 -xW -w" --enable-teuchos-abc \
--enable-mpi --with-mpi-compilers \
--with-libs="-lexpat" \
--with-blas="$MKL_PATH/libmkl_lapack.a $MKL_PATH/libmkl_ia32.a $MKL_PATH/libguide.a -lpthread" \
--with-lapack="-L$MKL_PATH -lmkl_lapack" \
--enable-tsfextended \
--enable-tsfcore \
--enable-tsfcore-epetra \
--enable-tsfcore-mpi \
--enable-tsfcore-aztecoo \
--enable-teuchos \
--enable-teuchos-expat \
--enable-ml \
--enable-teuchos-extended \
--disable-new-package \
--disable-ml-examples \
--enable-nox \
--enable-nox-tsf \
--enable-nox-tsf-examples \
--disable-loca \
--with-install="/usr/bin/install -c -p" \
--prefix=$BUILD_DIR


