#!/bin/sh

##################################################################
# Configuration of Trilinos for use with Sundance 2.0 
#
# Linux with Intel compilers, optimized for speed
# 
# Kevin Long, 21 September, 2004
#
##################################################################



#-------------------------------------------------------------------------
# We'll install into the build directory. The result of `pwd` will be used
# as the argument to the --prefix flag in configure.
#-------------------------------------------------------------------------
BUILD_DIR=`pwd`

#-------------------------------------------------------------------------
# Search for the intel compiler. I've installed my Intel stuff in 
# /usr/local/intel, so we'll try looking there first. If we don't find
# the C++ compiler there, we'll search for icc. 
#------------------------------------------------------------------------

if [ -x /usr/local/intel/bin/icc ]; then 
INTEL_DIR=/usr/local/intel/bin;
else
INTEL_DIR=`find / -name icc -printf '%h'`;
fi

#-------------------------------------------------------------------------
# Now that we've found the path to the Intel distribution, define the
# compilers and library search path. 
#-------------------------------------------------------------------------
INTEL_CXX=${INTEL_DIR}/icc
INTEL_CC=${INTEL_DIR}/icc
INTEL_LIB=${INTEL_DIR}/../lib

#-------------------------------------------------------------------------
# Now run configure
#
# A couple of things to note: 
# (1) If you don't have the Intel Fortran compiler (which I don't) then
#     you need to link against the Gnu fortran libraries. Linuxes differ 
#     regarding whether the fortran library is -lg77 or -lg2c. It's 
#     -lg2c on my system (gcc 3.3.1 on Suse 9.0) but your mileage may vary.
# (2) If MPI was built using Gnu, you'll need to link
#     against the Gnu standard linraries, and you must 
#     set the --cxxlib-gcc compiler flag, and you must specify the names
#     of the libraries. 
# (3) If MPI was built using GCC, e need to specify all the MPI libraries
#     and paths explcitly rather than using mpiCC. 
#------------------------------------------------------------------------

../configure --enable-mpi --with-mpi-libs="-lmpich -lpmpich" \
--with-mpi-incdir="/usr/local/include" \
CXX=${INTEL_CXX} \
CC=${INTEL_CC} \
CXXFLAGS="-O3 -finline-functions -cxxlib-gcc -I/usr/local/include" \
--with-ldflags=-L${INTEL_LIB} \
FLIBS="-lfrtbegin -lg2c -lm -lgcc_s -lstdc++ -lgcc" \
--with-blas="-L/usr/local/intel/mkl70/lib/32 -lmkl_lapack -lmkl_ia32" \
--enable-tsfextended \
--enable-tsfcore \
--enable-tsfcore-epetra \
--enable-tsfcore-mpi \
--enable-tsfcore-aztecoo \
--enable-teuchos \
--enable-expat \
--disable-ml \
--enable-teuchos-extended \
--disable-new-package \
--disable-ml-examples \
--enable-nox \
--enable-nox-tsf \
--enable-nox-tsf-examples \
--disable-loca \
--with-install="/usr/bin/install -c -p" \
--prefix=$BUILD_DIR




