#!/bin/sh

##################################################################
#
# Configuration of Trilinos for use with Sundance
#
##################################################################


BUILD_DIR=`pwd`

../configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-g -Wall" \
--with-libs="-lumfpack -lamd -lexpat" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-abc \
--enable-teuchos-complex --enable-teuchos-expat \
--enable-moocho \
--enable-belos \
--enable-belos-thyra \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--enable-epetra-thyra \
--enable-epetraext-thyra \
--enable-amesos-thyra \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--enable-ml-thyra \
--enable-prerelease \
--with-ml_nox \
--disable-ml-examples \
--disable-ml-tests \
--enable-aztecoo \
--enable-aztecoo-thyra \
--enable-ifpack \
--enable-ifpack-thyra \
--enable-nox \
--enable-nox-epetra \
--enable-nox-epetraext \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--prefix=$BUILD_DIR


