#!/bin/sh

##################################################################
# Configuration of Trilinos for use with the development version 
# of Sundance.
#
# This will NOT work with the old version of Sundance
##################################################################


BUILD_DIR=`pwd`

TRILINOS_DATA_DIR=${HOME}/Code/TrilinosData

../configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-g -O0 -Wall" \
--with-libs="-lumfpack -lamd" \
--disable-default-packages \
--enable-sundance \
--with-sundance-exodus \
--enable-sundance-tests \
--enable-sundance-examples \
--with-trilinosdatadir=${TRILINOS_DATA_DIR} \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-abc \
--enable-teuchos-complex \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--enable-aztecoo-thyra \
--enable-epetra-thyra \
--enable-anasazi-thyra \
--enable-amesos-thyra \
--enable-ifpack-thyra \
--enable-anasazi \
--enable-ml-thyra \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--disable-moocho \
--disable-moocho-thyra \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--config-cache \
--prefix=$BUILD_DIR




