#!/bin/sh

##################################################################
# Configuration of Trilinos for use with the development version 
# of Sundance.
##################################################################


BUILD_DIR=`pwd`

TRILINOS_DATA_DIR=${HOME}/Code/TrilinosData

../configure \
CXX=g++ CC=gcc FC=gfortran F77=gfortran \
CXXFLAGS="-g -O0 -Wall" \
--with-libs="-lumfpack -lamd" \
--with-incdirs="-I/usr/local/gcc-4.3.0/include" \
--with-ldflags="-L/usr/local/gcc-4.3.0/lib" \
--disable-default-packages \
--enable-sundance \
--enable-sundance-tests \
--with-sundance-exodus \
--with-trilinosdatadir=${TRILINOS_DATA_DIR} \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-abc \
--enable-teuchos-complex \
--enable-thyra \
--enable-aztecoo-thyra \
--enable-epetra-thyra \
--enable-amesos-thyra \
--enable-ifpack-thyra \
--enable-ml-thyra \
--enable-stratimikos \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--config-cache \
--prefix=$BUILD_DIR




