#!/bin/sh

##################################################################
# Configuration of Trilinos and Sundance
##################################################################


BUILD_DIR=`pwd`

TRILINOS_DATA_DIR=${HOME}/Code/TrilinosData

../configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-O3 -Wall  -finline-functions -funroll-loops" \
--with-libs="-lumfpack -lamd" \
--disable-default-packages \
--enable-sundance \
--enable-sundance-tests \
--enable-python \
--with-sundance-exodus \
--with-trilinosdatadir=${TRILINOS_DATA_DIR} \
--enable-teuchos --enable-teuchos-extended \
--enable-teuchos-complex \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--enable-aztecoo-thyra \
--enable-epetra-thyra \
--enable-amesos-thyra \
--enable-ifpack-thyra \
--enable-ml-thyra \
--enable-anasazi-thyra \
--enable-anasazi \
--enable-stratimikos \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--config-cache \
--prefix=$BUILD_DIR




