#ifndef AMESOS2_ABSTRACTCONCRETEMATRIXADAPTER_DEF
#define AMESOS2_ABSTRACTCONCRETEMATRIXADAPTER_DEF

#include "Amesos2_TpetraRowMatrix_AbstractMatrixAdapter_def.hpp"
#ifdef HAVE_AMESOS2_EPETRA
#include "Amesos2_EpetraRowMatrix_AbstractMatrixAdapter_def.hpp"
#endif

#endif
