if ("${REPOSITORY_NAME}" STREQUAL "")
  set(REPOSITORY_NAME TriBITS)
endif()

set(${REPOSITORY_NAME}_VERSION 0.9)
set(${REPOSITORY_NAME}_MAJOR_VERSION 00)
set(${REPOSITORY_NAME}_MAJOR_MINOR_VERSION 000900)
set(${REPOSITORY_NAME}_VERSION_STRING "0.9 (Dev)")
set(${REPOSITORY_NAME}_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
