IF ("${REPOSITORY_NAME}" STREQUAL "")
  SET(REPOSITORY_NAME TriBITS)
ENDIF()

SET(${REPOSITORY_NAME}_VERSION 0.9)
SET(${REPOSITORY_NAME}_MAJOR_VERSION 00)
SET(${REPOSITORY_NAME}_MAJOR_MINOR_VERSION 000900)
SET(${REPOSITORY_NAME}_VERSION_STRING "0.9 (Dev)")
SET(${REPOSITORY_NAME}_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
