SET(LIB_REQUIRED_DEP_PACKAGES Epetra Isorropia AztecOO Belos Ifpack Amesos Teuchos)
SET(LIB_OPTIONAL_DEP_PACKAGES Tpetra Zoltan2 Amesos2)
SET(TEST_REQUIRED_DEP_PACKAGES ML)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS MPI)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS ParMETIS SuperLU)


