#ifndef STK_NGP_TEST_NGPTESTDEVICEMACROS_HPP
#define STK_NGP_TEST_NGPTESTDEVICEMACROS_HPP

#include <Kokkos_Macros.hpp>

#define NGP_TEST_FUNCTION KOKKOS_FUNCTION
#define NGP_TEST_INLINE KOKKOS_INLINE_FUNCTION

#endif
