#! /usr/bin/env bash

EXTRA_ARGS=$@

PROJECT_NAME=Trilinos
SOURCE_DIR=../$PROJECT_NAME

rm -fr CMakeCache.txt CMakeFiles/

cmake \
-D CMAKE_CXX_COMPILER:FILEPATH=g++ \
-D CMAKE_C_COMPILER:FILEPATH=gcc \
-D CMAKE_Fortran_COMPILER:FILEPATH=gfortran \
-D HAVE_GCC_ABI_DEMANGLE:BOOL=ON \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D DART_TESTING_TIMEOUT:STRING=600 \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS=ON \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_SECONDARY_STABLE_CODE=ON \
-D Trilinos_ENABLE_Optika=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Boost_INCLUDE_DIRS=/Users/bmpersc/lib/boost_1_38_0 \
-DNetcdf_LIBRARY_DIRS=/Users/bmpersc/lib/netcdf-4.0/lib \
-DNetcdf_INCLUDE_DIRS=/Users/bmpersc/lib/netcdf-4.0/include \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
$EXTRA_ARGS \
$SOURCE_DIR

if [ $? == 0 ]; then
  make package_source
else
  echo "Configure failed no tarballs created."
fi
