SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Xpetra)
SET(LIB_OPTIONAL_DEP_PACKAGES Amesos Amesos2 Epetra EpetraExt KokkosClassic Teko
                              Ifpack Ifpack2 ML Tpetra Zoltan Zoltan2 Stratimikos ThyraTpetraAdapters Isorropia)
SET(TEST_REQUIRED_DEP_PACKAGES )
SET(TEST_OPTIONAL_DEP_PACKAGES AztecOO Galeri Belos)
SET(LIB_REQUIRED_DEP_TPLS BLAS LAPACK)
SET(LIB_OPTIONAL_DEP_TPLS Boost)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

