
SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
#  Core        core        PS REQUIRED
  BlackBox    blackbox    PS OPTIONAL
  Implicit    implicit    PS OPTIONAL
  )

# NOTE: The above subpackages are automatically listed as dependencies

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
