

SET(CMAKE_EXECUTABLE_SUFFIX ".exe")


#
# Process the COMM arguments
#
# NOTE: The COMM array arguments is passed as ${ARGN}
#

FUNCTION( PACKAGE_PROCESS_COMM_ARGS  ADD_SERIAL_FEATURE  ADD_MPI_FEATURE )

  SET(COMM_ARRAY ${ARGN})

  IF (COMM_ARRAY)
    SET(${ADD_SERIAL_FEATURE} OFF PARENT_SCOPE)
    SET(${ADD_MPI_FEATURE} OFF PARENT_SCOPE)
    FOREACH(COMM ${COMM_ARRAY})
      IF(COMM STREQUAL "serial")
        SET(${ADD_SERIAL_FEATURE} ON PARENT_SCOPE)
      ELSEIF (COMM STREQUAL "mpi")
        SET(${ADD_MPI_FEATURE} ON PARENT_SCOPE)
      ELSE()
        MESSAGE(SEND_ERROR "Error, the COMM value '${COMM}' is not valid."
          "  Only 'mpi' and 'serial' are allowed.")
      ENDIF()
    ENDFOREACH()
  ELSE()
    SET(${ADD_MPI_FEATURE} ON PARENT_SCOPE)
    SET(${ADD_SERIAL_FEATURE} ON PARENT_SCOPE)
  ENDIF()

  IF (TPL_ENABLE_MPI)
    SET(${ADD_SERIAL_FEATURE} OFF PARENT_SCOPE)
  ELSE()
    SET(${ADD_MPI_FEATURE} OFF PARENT_SCOPE)
  ENDIF()

ENDFUNCTION()
