SET(${PROJECT_NAME}_PACKAGES_FILE_NAME ${PROJECT_NAME}Packages.cmake)

SET(${PROJECT_NAME}_EXTRA_EXTERNAL_REPOS_FILE_NAME ExtraExternalRepositories.cmake)

SET(${PROJECT_NAME}_EXTRA_PACKAGES_FILE_NAME Extra${PROJECT_NAME}Packages.cmake)

SET(${PROJECT_NAME}_PACKAGE_DEPS_XML_FILE_NAME ${PROJECT_NAME}PackageDependencies.xml)

SET(${PROJECT_NAME}_CDASH_SUBPROJECT_DEPS_XML_FILE_NAME CDashSubprojectDependencies.xml)

SET(${PROJECT_NAME}_PACKAGE_DEPS_TABLE_HTML_FILE_NAME ${PROJECT_NAME}PackageDependenciesTable.html)
