SET(Trilinos_VERSION 10.2)
SET(Trilinos_MAJOR_VERSION 10)
SET(Trilinos_MAJOR_MINOR_VERSION 100200)
SET(Trilinos_VERSION_STRING "11.2 (Dev)")
SET(Trilinos_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
