#ifndef CTHULHU_EPETRAEXPORT_HPP
#define CTHULHU_EPETRAEXPORT_HPP

/* this file is automatically generated - do not edit (see script/epetra.py) */

#include "Cthulhu_EpetraConfigDefs.hpp"

#include "Cthulhu_Export.hpp"

#include "Cthulhu_EpetraMap.hpp"//TMP

#include "Epetra_Export.h"

// Note: 'export' is a reserved keyword in C++. Do not use 'export' as a variable name.

namespace Cthulhu {

  // TODO: move that elsewhere
  const Epetra_Export & toEpetra(const Export<int, int> &);
  //

  class EpetraExport
    : public Export<int, int>
  {

    typedef int LocalOrdinal;
    typedef int GlobalOrdinal;
    typedef Kokkos::DefaultNode::DefaultNodeType Node;

  public:

    //! @name Constructor/Destructor Methods
    //@{

    //! Constructs a Export object from the source and target Map.
    EpetraExport(const RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > > &source, const RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > > &target);

    //! copy constructor.
    EpetraExport(const Export< LocalOrdinal, GlobalOrdinal, Node > &import);

    //! destructor.
    ~EpetraExport() { }

    //@}

    //! @name Export Attribute Methods
    //@{

    //! Returns the number of entries that are identical between the source and target maps, up to the first different ID.
    size_t getNumSameIDs() const { return export_->NumSameIDs(); }

    //! Returns the number of entries that are local to the calling image, but not part of the first getNumSameIDs() entries.
    size_t getNumPermuteIDs() const { return export_->NumPermuteIDs(); }

    //! Returns the Source Map used to construct this exporter.
    const RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > >  getSourceMap() const { return toCthulhu(export_->SourceMap()); }

    //! Returns the Target Map used to construct this exporter.
    const RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > >  getTargetMap() const { return toCthulhu(export_->TargetMap()); }

    //@}

    //! @name Cthulhu specific
    //@{

    //! EpetraExport constructor to wrap a Epetra_Export object
    EpetraExport(const RCP<const Epetra_Export> &exp) : export_(exp) {  }

    //! Get the underlying Epetra export
    RCP< const Epetra_Export> getEpetra_Export() const { return export_; }

    //@}
    
  private:
    
    RCP<const Epetra_Export> export_;

  }; // EpetraExport class

} // Cthulhu namespace

#endif // CTHULHU_EPETRAEXPORT_HPP
