
#
# Set the options specific to this build
#

SET(COMM_TYPE SERIAL)
SET(BUILD_TYPE DEBUG)
SET(BUILD_DIR_NAME SERIAL_DEBUG)

SET(CTEST_DO_COVERAGE_TESTING TRUE)
SET(CTEST_DO_MEMORY_TESTING TRUE)


SET(CTEST_INITIAL_CACHE "

CMAKE_CXX_FLAGS_${BUILD_TYPE}:STRING=-g -O0 -fprofile-arcs -ftest-coverage
CMAKE_C_FLAGS_${BUILD_TYPE}:STRING=-g -O0 -fprofile-arcs -ftest-coverage
CMAKE_Fortran_FLAGS_${BUILD_TYPE}:STRING=-g -O0 -fprofile-arcs -ftest-coverage

DART_TESTING_TIMEOUT:STRING=600
CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE

Trilinos_ENABLE_ALL_PACKAGES:BOOL=ON

Trilinos_ENABLE_DEPENCENCY_UNIT_TESTS:BOOL=OFF

Trilinos_ENABLE_TESTS:BOOL=ON

Trilinos_ENABLE_DEBUG:BOOL=ON

Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON

TPL_ENABLE_Boost:BOOL=ON

EpetraExt_BUILD_GRAPH_REORDERINGS:BOOL=ON
EpetraExt_BUILD_BDF:BOOL=ON

")


#
# Read in the platform-independent and platform-dependent options
#

INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestSupport.godel.cmake")
