
INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestDriverCore.godel.gcc.cmake")

#
# Set the options specific to this build case
#

SET(COMM_TYPE MPI)
SET(BUILD_TYPE RELEASE)
SET(BUILD_DIR_NAME MPI_OPT)

#SET(CTEST_DO_COVERAGE_TESTING TRUE)
#SET(CTEST_DO_MEMORY_TESTING TRUE)

SET(COVERAGE_FLAGS "-fprofile-arcs -ftest-coverage")

SET( EXTRA_CONFIGURE_OPTIONS
  "-DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}"
  "-DCMAKE_CXX_FLAGS:STRING=\"${COVERAGE_FLAGS}\""
  "-DCMAKE_C_FLAGS:STRING=\"${COVERAGE_FLAGS}\""
  "-DCMAKE_Fortran:STRING=\"${COVERAGE_FLAGS}\""
  "-DCMAKE_EXE_LINKER_FLAGS:STRING=\"${COVERAGE_FLAGS}\""
  "-DDART_TESTING_TIMEOUT:STRING=600"
  #"-DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE"
  "-DTrilinos_ENABLE_DEPENCENCY_UNIT_TESTS:BOOL=OFF"
  "-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON"
  "-DTPL_ENABLE_Boost:BOOL=ON"
  "-DTPL_ENABLE_ParMETIS:BOOL=ON"
  "-DParMETIS_LIBRARY_DIRS:PATH=/home/kddevin/code/ParMETIS3_1"
  "-DTPL_ENABLE_Scotch:BOOL=ON"
  "-DScotch_INCLUDE_DIRS:PATH=/home/kddevin/code/scotch_5.1/include"
  "-DScotch_LIBRARY_DIRS:PATH=/home/kddevin/code/scotch_5.1/lib"
  )

#
# Set the rest of the system-specific options and run the dashboard build/test
#

TRILINOS_SYSTEM_SPECIFIC_CTEST_DRIVER()
