
#
# Set the options specific to this build
#

SET(COMM_TYPE SERIAL)
SET(BUILD_TYPE RELEASE)
SET(BUILD_DIR_NAME SERIAL_PERF)


SET(CTEST_INITIAL_CACHE "

CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++
CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc
CMAKE_Fortran_COMPILER:FILEPATH=/usr/bin/gfortran

CMAKE_CXX_FLAGS_${BUILD_TYPE}:STRING=-03
CMAKE_C_FLAGS_${BUILD_TYPE}:STRING=-03
CMAKE_Fortran_FLAGS_${BUILD_TYPE}:STRING=-O5

CMAKE_EXE_LINKER_FLAGS:STRING=-lm

DART_TESTING_TIMEOUT:STRING=600
CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE

Trilinos_ENABLE_Teuchos:BOOL=ON
Trilinos_ENABLE_Sacado:BOOL=ON

Trilinos_ENABLE_DEPENCENCY_UNIT_TESTS:BOOL=OFF

Trilinos_ENABLE_PERFORMANCE_TESTS:BOOL=ON

Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON

TPL_ENABLE_Boost:BOOL=ON

")


#
# Read in the platform-independent and platform-dependent options
#

INCLUDE("${CTEST_SCRIPT_DIRECTORY}/TrilinosCTestSupport.godel.cmake")
