FUNCTION(SET_CACHE_VAR  VAR_NAME  VAR_VALUE  CACHE_STR  TYPE_STR)
  IF ("${${VAR_NAME}}" STREQUAL "")
    MESSAGE("-- " "Setting ${VAR_NAME}='${VAR_VALUE}' by default")
    SET(${VAR_NAME} "${VAR_VALUE}" ${CACHE_STR}  ${TYPE_STR}
      "Set in ${CMAKE_CURRENT_LIST_FILE}")
  ENDIF()
ENDFUNCTION()

FUNCTION(SET_BOOL_CACHE_VAR  VAR_NAME  VAR_VALUE)
  SET_CACHE_VAR(${VAR_NAME}  ${VAR_VALUE}  CACHE  BOOL)
ENDFUNCTION()


SET(CMAKE_INSTALL_PREFIX "$ENV{TRILINOS_INSTALL_DIR}" CACHE FILEPATH "Install location")
SET_BOOL_CACHE_VAR(CMAKE_EXPORT_COMPILE_COMMANDS ON)


SET_BOOL_CACHE_VAR(TPL_ENABLE_MPI ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_BLAS ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_LAPACK ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_HDF5 ON)
SET_BOOL_CACHE_VAR(Netcdf_ALLOW_MODERN ON)
SET_BOOL_CACHE_VAR(BUILD_SHARED_LIBS ON)

SET_BOOL_CACHE_VAR(Teuchos_KOKKOS_PROFILING ON)
SET_BOOL_CACHE_VAR(Teuchos_ENABLE_GCC_DEMANGLE ON)
SET_BOOL_CACHE_VAR(Teuchos_ENABLE_STACKTRACE ON)

SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Kokkos ON)
SET_BOOL_CACHE_VAR(Kokkos_ENABLE_EXAMPLES OFF)

SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_ALL_COMPONENTS OFF)
SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_COMPONENT_BATCHED ON)
SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_COMPONENT_BLAS ON)
SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_COMPONENT_LAPACK ON)
SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_COMPONENT_SPARSE ON)
SET_BOOL_CACHE_VAR(KokkosKernels_ENABLE_COMPONENT_GRAPH ON)

SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Belos ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Stratimikos ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Xpetra ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Tpetra ON)
SET_BOOL_CACHE_VAR(Tpetra_ENABLE_EXAMPLES ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Ifpack2 ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Amesos2 ON)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_MueLu ON)
SET_BOOL_CACHE_VAR(MueLu_ENABLE_EXAMPLES ON)
SET_BOOL_CACHE_VAR(MueLu_ENABLE_Intrepid2 OFF)

SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Epetra OFF)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_EpetraExt OFF)
SET_BOOL_CACHE_VAR(Trilinos_ENABLE_ML OFF)

set(CMAKE_CXX_COMPILER_LAUNCHER "ccache" CACHE STRING "")
set(CMAKE_C_COMPILER_LAUNCHER "ccache" CACHE STRING "")
set(CMAKE_GENERATOR "Ninja" CACHE STRING "")

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fdiagnostics-color=always" CACHE STRING "" FORCE)
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fdiagnostics-color=always" CACHE STRING "" FORCE)


set(PYTHON3_EXECUTABLE "$ENV{PYTHON_ROOT}/bin/python3" CACHE FILEPATH "")

SET_BOOL_CACHE_VAR(Trilinos_ENABLE_PyTrilinos2 ON)
SET_BOOL_CACHE_VAR(PyTrilinos2_ENABLE_TESTS ON)
SET_BOOL_CACHE_VAR(PyTrilinos2_ENABLE_EXAMPLES ON)
SET_BOOL_CACHE_VAR(PyTrilinos2_BINDER_VERBOSE ON)


# SET(Trilinos_WARNINGS_MODE "WARN" CACHE STRING "Trilinos warnings mode")
