#pragma once
#include <pybind11/smart_holder.h>
#include <ROL_Vector.hpp>
#include <ROL_Vector_SimOpt.hpp>
#include <ROL_Objective.hpp>
#include <ROL_Objective_SimOpt.hpp>
#include <ROL_Reduced_Objective_SimOpt.hpp>
#include <ROL_Constraint.hpp>
#include <ROL_Constraint_SimOpt.hpp>
#include <Teuchos_RCP.hpp>
