
SET(TribitsExProj_VERSION 0.1)
SET(TribitsExProj_MAJOR_VERSION 0)
SET(TribitsExProj_MAJOR_MINOR_VERSION 000100)
SET(TribitsExProj_VERSION_STRING "0.1 (Dev)")
SET(TribitsExProj_ENABLE_DEVELOPMENT_MODE_DEFAULT ON)
SET(TribitsExProj_REPOSITORY_BRANCH "master" CACHE INTERNAL "")
SET(TribitsExProj_TESTING_TRACK "" CACHE INTERNAL "")
