#ifndef XPETRA_PARAMETERS_FWD_HPP
#define XPETRA_PARAMETERS_FWD_HPP

namespace Xpetra {
  class Parameters;
}

#ifndef XPETRA_PARAMETERS_SHORT
#define XPETRA_PARAMETERS_SHORT
#endif

#endif // XPETRA_PARAMETERS_FWD_HPP
