#ifndef XPETRA_EPETRACRSGRAPH_FWD_HPP
#define XPETRA_EPETRACRSGRAPH_FWD_HPP

namespace Xpetra {
  class EpetraCrsGraph;
}

#ifndef XPETRA_EPETRACRSGRAPH_SHORT
#define XPETRA_EPETRACRSGRAPH_SHORT
#endif

#endif // XPETRA_EPETRACRSGRAPH_FWD_HPP
