#ifndef XPETRA_EPETRAINTVECTOR_FWD_HPP
#define XPETRA_EPETRAINTVECTOR_FWD_HPP

namespace Xpetra {
  class EpetraIntVector;
}

#ifndef XPETRA_EPETRAINTVECTOR_SHORT
#define XPETRA_EPETRAINTVECTOR_SHORT
#endif

#endif // XPETRA_EPETRAINTVECTOR_FWD_HPP
