#ifndef XPETRA_EPETRACRSMATRIX_FWD_HPP
#define XPETRA_EPETRACRSMATRIX_FWD_HPP

namespace Xpetra {
  class EpetraCrsMatrix;
}

#ifndef XPETRA_EPETRACRSMATRIX_SHORT
#define XPETRA_EPETRACRSMATRIX_SHORT
#endif

#endif // XPETRA_EPETRACRSMATRIX_FWD_HPP
