SET(LIB_REQUIRED_DEP_PACKAGES Tpetra KokkosClassic Epetra Teuchos Xpetra)
SET(LIB_OPTIONAL_DEP_PACKAGES Anasazi)
SET(TEST_REQUIRED_DEP_PACKAGES Tpetra KokkosClassic Epetra Teuchos Xpetra Galeri)
SET(TEST_OPTIONAL_DEP_PACKAGES Zoltan)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS Scotch AMD CCOLAMD OVIS)
SET(TEST_REQUIRED_DEP_TPLS) 
SET(TEST_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS Scotch AMD CCOLAMD OVIS)

