SET(LIB_REQUIRED_DEP_PACKAGES Tpetra Epetra Teuchos Xpetra Zoltan)
SET(LIB_OPTIONAL_DEP_PACKAGES SCOREC)
SET(TEST_REQUIRED_DEP_PACKAGES Tpetra Epetra Teuchos Xpetra Galeri Pamgen Zoltan)
SET(TEST_OPTIONAL_DEP_PACKAGES SCOREC)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS Scotch AMD CCOLAMD OVIS)
SET(TEST_REQUIRED_DEP_TPLS) 
SET(TEST_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS Scotch AMD CCOLAMD OVIS)

