SET(LIB_REQUIRED_DEP_PACKAGES Tpetra TeuchosCore TeuchosComm TeuchosParameterList Xpetra Zoltan)
SET(LIB_OPTIONAL_DEP_PACKAGES SCORECgmi SCORECpcu SCORECapf SCORECmds SCORECparma)
SET(TEST_REQUIRED_DEP_PACKAGES Tpetra TeuchosCore TeuchosComm TeuchosParameterList Xpetra Zoltan)
SET(TEST_OPTIONAL_DEP_PACKAGES Galeri Pamgen SCORECgmi SCORECpcu SCORECapf SCORECmds SCORECparma)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS PuLP Scotch SARMA AMD OVIS TopoManager)
SET(TEST_REQUIRED_DEP_TPLS) 
SET(TEST_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS PuLP Scotch SARMA AMD OVIS TopoManager)

