COMMON_DEPENDENT_FILES = \
  Makefile \
  ../generate-guide.sh \
  ../TribitsCoreDetailedReference.rst \
  ../TribitsGuidesBody.rst \
  ../TribitsGuidesReferences.rst \
  ../TribitsFAQ.rst \
  ../TribitsHistory.rst \
  ../TribitsPackageNotCMakePackage.rst \
  ../TribitsDesignConsiderations.rst \
  ../TribitsToolsDocumentation.rst \
  ../TribitsStandardTPLsList.txt \
  ../TribitsCommonTPLsList.txt \
  ../checkin-test-help.txt \
  ../gitdist-help.txt \
  ../gitdist-dist-help-overview.txt \
  ../gitdist-dist-help-repo-selection-and-setup.txt \
  ../gitdist-dist-help-dist-repo-status.txt \
  ../gitdist-dist-help-repo-versions.txt \
  ../gitdist-dist-help-aliases.txt \
  ../gitdist-dist-help-usage-tips.txt \
  ../gitdist-dist-help-script-dependencies.txt \
  ../gitdist-dist-help-all.txt \
  ../clone_extra_repos-help.txt \
  ../snapshot-dir-help.txt \
  ../is_checkin_tested_commit.txt \
  ../get-tribits-packages-from-files-list.txt \
  ../install_devtools-help.txt \
  ../TriBITS.README.DIRECTORY_CONTENTS.rst \
  $(wildcard ../*.cmake) \
  TribitsMacroFunctionDoc.rst \
  UtilsMacroFunctionDoc.rst

# NOTE: We *don't* want to rebuild the file if only the version has changed we
# don't add a dependency on TribitsGitVersion.txt!

# NOTE: The above paths are relative the the users_guide/ and
# maintainers_guide/ subdirs.
