MACRO(EPETRA_ADD_TEST TEST_DIR_NAME TEST_NAME)
  ADD_SUBDIRECTORY(${TEST_DIR_NAME})
  SET(TEST_EXEC_NAME ${TEST_NAME}_test)

  SET(SOURCES )
  FOREACH(SOURCE ${ARGN})
    SET(SOURCES ${SOURCES} ${TEST_DIR_NAME}/${SOURCE})
  ENDFOREACH(SOURCE)

  IF(TEST_ARGS)
    SET(TEST_ARGS ${TEST_ARGS} -v)
  ELSE(TEST_ARGS)
    SET(TEST_ARGS -v)
  ENDIF(TEST_ARGS)

  INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR}/${TEST_DIR_NAME})
  INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/${TEST_DIR_NAME})
  INCLUDE_DIRECTORIES(${epetra_BINARY_DIR}/src)
  INCLUDE_DIRECTORIES(${epetra_SOURCE_DIR}/src)

  ADD_DEFINITIONS(-DHAVE_CONFIG_H)

  ADD_EXECUTABLE(${TEST_EXEC_NAME} ${SOURCES})
  SET_TARGET_PROPERTIES(${TEST_EXEC_NAME} 
    PROPERTIES OUTPUT_NAME ${TEST_DIR_NAME}/${TEST_EXEC_NAME}
  )
  TARGET_LINK_LIBRARIES(${TEST_EXEC_NAME} epetra ${LAPACK_LIBRARY} ${BLAS_LIBRARY})

  IF(ENABLE_MPI)
    INCLUDE_DIRECTORIES(${MPI_INCLUDE_PATH})
    TARGET_LINK_LIBRARIES(${TEST_EXEC_NAME} ${MPI_LIBRARY})
  ENDIF(ENABLE_MPI)

  IF(ENABLE_TESTS)
    ADD_TEST(${TEST_NAME} ${TEST_DIR_NAME}/${TEST_EXEC_NAME} ${TEST_ARGS})
    IF(ENABLE_MPI)
      ADD_TEST(${TEST_NAME}_MPI ${MPI_EXECUTABLE} ${TEST_DIR_NAME}/${TEST_EXEC_NAME} ${TEST_ARGS})
    ENDIF(ENABLE_MPI)
  ENDIF(ENABLE_TESTS)

  SET(TEST_ARGS)
ENDMACRO(EPETRA_ADD_TEST) 

