if(NOT NUMBER_FILE)
    message(FATAL_ERROR "NUMBER_FILE must be specified")
endif()

if(EXISTS ${CMAKE_CURRENT_BINARY_DIR}/../binder/pyrol_${NUMBER_FILE}.cpp)
    MATH(EXPR INDEX "${NUMBER_FILE}+1")
    while (EXISTS ${CMAKE_CURRENT_BINARY_DIR}/../binder/pyrol_${INDEX}.cpp)
        MATH(EXPR INDEX "${INDEX}+1")
    endwhile()
    MATH(EXPR INDEX "${INDEX}-1")
    message(FATAL_ERROR "File pyrol_${NUMBER_FILE}.cpp exists; please rerun the configuration with PyROL_BINDER_NUM_FILES at least equal to ${INDEX}.")
endif()
