if(CMAKE_PROJECT_NAME STREQUAL "SEACAS")
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_PACKAGES Exodus SuplibC SuplibCpp
  )
else()
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_PACKAGES SEACASExodus SEACASSuplibC SEACASSuplibCpp
  )
endif()
