if (SHOW_TEST_REQUIRED_PACKAGE_DEP)
  set(TEST_REQUIRED_PACKAGES  Triutils)
endif()

if (SHOW_TEST_REQUIRED_TPL_DEP)
  set(TEST_REQUIRED_PACKAGES  ${TEST_REQUIRED_PACKAGES}  AMD)
endif()

tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES Teuchos Epetra
  LIB_OPTIONAL_PACKAGES Triutils
  LIB_OPTIONAL_PACKAGES UMFPACK AMD PETSC
  TEST_REQUIRED_PACKAGES ${TEST_REQUIRED_PACKAGES}
  )
