###############################################################################
#
#              Standard ATDM Configuration of Trilnos
#
###############################################################################

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/ATDMDevEnvUtils.cmake")

#
# Base options for all ATDM bulids for Trilinos
#

ATDM_SET_ENABLE(TPL_ENABLE_MPI ON)

#
# A) Assert the right env vars are set
#

ASSERT_DEFINED(ENV{BLAS_LIB})
ASSERT_DEFINED(ENV{LAPACK_LIB})
ASSERT_DEFINED(ENV{BOOST_ROOT})
ASSERT_DEFINED(ENV{HDF5_ROOT})
ASSERT_DEFINED(ENV{NETCDF_ROOT})

#
# B) Set the comilers
#

ASSERT_DEFINED(ENV{MPICC})
ASSERT_DEFINED(ENV{MPICXX})
ASSERT_DEFINED(ENV{MPIF90})

ATDM_SET(CMAKE_C_COMPILER "$ENV{MPICC}" CACHE FILEPATH)
ATDM_SET(CMAKE_CXX_COMPILER "$ENV{MPICXX}" CACHE FILEPATH)
ATDM_SET(CMAKE_Fortran_COMPILER "$ENV{MPIF90}" CACHE FILEPATH)
ATDM_SET_ENABLE(Trilinos_ENABLE_Fortran OFF)

#
# C) Set up basic compiler flags, link flags etc.
#

ATDM_SET(BUILD_SHARED_LIBS "$ENV{SHARED_LIBS}" CACHE BOOL)
ATDM_SET(CMAKE_BUILD_TYPE "$ENV{BUILD_TYPE}" CACHE STRING)
ATDM_SET(CMAKE_C_FLAGS "$ENV{EXTRA_C_FLAGS}" CACHE STRING)
ATDM_SET(CMAKE_CXX_FLAGS "$ENV{EXTRA_CXX_FLAGS}" CACHE STRING)

#
# D) Set up other misc options
#

ATDM_SET(CMAKE_SKIP_RULE_DEPENDENCY ON CACHE BOOL)
ATDM_SET(CMAKE_INSTALL_PREFIX "$ENV{INSTALL_DIR}" CACHE PATH)
ATDM_SET(CMAKE_VERBOSE_MAKEFILE OFF CACHE BOOL)
ATDM_SET(MPI_EXEC_POST_NUMPROCS_FLAGS "$ENV{MPI_POST_FLAG}" CACHE STRING)
ATDM_SET(Trilinos_VERBOSE_CONFIGURE OFF CACHE BOOL)
ATDM_SET(Trilinos_ENABLE_DEBUG OFF CACHE BOOL)
ATDM_SET(Trilinos_ENABLE_EXPLICIT_INSTANTIATION ON CACHE BOOL)
ATDM_SET(Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES ON CACHE BOOL)
ATDM_SET(Trilinos_ENABLE_DEVELOPMENT_MODE OFF CACHE BOOL)
ATDM_SET(Trilinos_ENABLE_OpenMP "$ENV{USE_OPENMP}" CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_OpenMP "$ENV{USE_OPENMP}" CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_Pthread "$ENV{USE_PTHREADS}" CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_Cuda_UVM "$ENV{USE_CUDA}" CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA ON CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_Cuda_Lambda "$ENV{USE_CUDA}" CACHE BOOL)
ATDM_SET(Kokkos_ENABLE_Debug_Bounds_Check "$ENV{BOUNDS_CHECK}" CACHE BOOL)
ATDM_SET(MueLu_ENABLE_Experimental ON CACHE BOOL)
ATDM_SET(Panzer_ENABLE_FADTYPE "Sacado::Fad::DFad<RealType>" CACHE STRING)
ATDM_SET(Panzer_ENABLE_TESTS ON CACHE BOOL)
ATDM_SET(Phalanx_KOKKOS_DEVICE_TYPE "$ENV{NODE_TYPE}" CACHE STRING)
ATDM_SET(Phalanx_SHOW_DEPRECATED_WARNINGS OFF CACHE BOOL)
ATDM_SET(Tpetra_INST_CUDA "$ENV{USE_CUDA}" CACHE BOOL)
ATDM_SET(Xpetra_ENABLE_Experimental ON CACHE BOOL)

#
# E) Set up disables
#

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/ATDMDisables.cmake")

#
# F) TPL locations and enables
#
# Since this is special ATDM configuration of Trilinos, it makes sense to go
# ahead and enable all of the TPLs by default that are used by the ATDM
# applications since.
#

# Pthread
ATDM_SET_ENABLE(TPL_ENABLE_Pthread OFF)

# DLLib
ATDM_SET_ENABLE(TPL_ENABLE_DLlib ON) 

# BLAS
ATDM_SET_ENABLE(TPL_ENABLE_BLAS ON)
ATDM_SET(TPL_BLAS_LIBRARIES "$ENV{BLAS_LIB}" CACHE FILEPATH)

# Boost
ATDM_SET_ENABLE(TPL_ENABLE_Boost ON)
ATDM_SET(Boost_INCLUDE_DIRS "$ENV{BOOST_ROOT}/include" CACHE FILEPATH)
ATDM_SET(TPL_Boost_LIBRARIES
   "$ENV{BOOST_ROOT}/lib/libboost_program_options.so;$ENV{BOOST_ROOT}/lib/libboost_system.so"
  CACHE FILEPATH)

# BoostLib
ATDM_SET_ENABLE(TPL_ENABLE_BoostLib ON)
ATDM_SET(BoostLib_INCLUDE_DIRS "$ENV{BOOST_ROOT}/include" CACHE FILEPATH)
ATDM_SET(TPL_BoostLib_LIBRARIES
  "$ENV{BOOST_ROOT}/lib/libboost_program_options.a;$ENV{BOOST_ROOT}/lib/libboost_system.a"
   CACHE FILEPATH)

# HWLOC
#ATDM_SET_ENABLE(TPL_ENABLE_HWLOC ON)  # ToDo: Put in logic for this
ATDM_SET(TPL_HWLOC_LIBRARIES "$ENV{HWLOC_LIBS}" CACHE FILEPATH)

# LAPACK
ATDM_SET_ENABLE(TPL_ENABLE_LAPACK ON)
ATDM_SET(TPL_LAPACK_LIBRARIES "$ENV{LAPACK_LIB}" CACHE FILEPATH)

# HDF5
ATDM_SET_ENABLE(TPL_ENABLE_HDF5 ON)
ATDM_SET(HDF5_INCLUDE_DIRS "$ENV{HDF5_ROOT}/include" CACHE FILEPATH)
IF (NOT "$ENV{HDF5_LIBS}")
  SET(HDF5_LIBS
    "$ENV{HDF5_ROOT}/lib/libhdf5_hl.a;$ENV{HDF5_ROOT}/lib/libhdf5.a;-lz;-ldl")
ENDIF()
ATDM_SET(TPL_HDF5_LIBRARIES "${HDF5_LIBS}" CACHE FILEPATH)

# Netcdf
ATDM_SET_ENABLE(TPL_ENABLE_Netcdf ON)
IF (NOT "$ENV{NETCDF_LIBS}")
  SET(NETCDF_LIBS
    "$ENV{NETCDF_ROOT}/lib/libnetcdf.a;$ENV{HDF5_ROOT}/lib/libhdf5_hl.a;$ENV{HDF5_ROOT}/lib/libhdf5.a;-lz;-ldl")
ENDIF()
ATDM_SET(Netcdf_INCLUDE_DIRS "$ENV{NETCDF_ROOT}/include" CACHE FILEPATH)
ATDM_SET(TPL_Netcdf_LIBRARIES "$ENV{NETCDF_LIBS}" CACHE FILEPATH)
