SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Epetra)
SET(LIB_OPTIONAL_DEP_PACKAGES Amesos EpetraExt AztecOO)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES Galeri)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS HYPRE HIPS SuperLU SPARSKIT)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS HYPRE SuperLU SPARSKIT)

