#ifndef KOKKOS_ARRAY_CONFIG_H
#define KOKKOS_ARRAY_CONFIG_H

#define KOKKOSARRAY_HAVE_MPI
#define KOKKOSARRAY_HAVE_PTHREAD

/*
#undef KOKKOSARRAY_HAVE_CUDA
#undef KOKKOSARRAY_HAVE_Winthread
#undef KOKKOSARRAY_HAVE_OPENMP
#undef KOKKOSARRAY_HAVE_HWLOC
*/

#endif

