#ifndef KOKKOSCLASSIC_DEFAULTNODE_CONFIG_H_
#define KOKKOSCLASSIC_DEFAULTNODE_CONFIG_H_

#define KOKKOSCLASSIC_DEFAULTNODE Kokkos::TPINode
#define HAVE_KOKKOSCLASSIC_DEFAULTNODE_TPINODE
/* #undef HAVE_KOKKOSCLASSIC_DEFAULTNODE_TBBNODE */
/* #undef HAVE_KOKKOSCLASSIC_DEFAULTNODE_OPENMPNODE */
/* #undef HAVE_KOKKOSCLASSIC_DEFAULTNODE_THRUSTGPUNODE */
/* #undef HAVE_KOKKOSCLASSIC_DEFAULTNODE_SERIALNODE */

#endif /* KOKKOSCLASSIC_DEFAULTNODE_CONFIG_H_ */
