

/* Options */

#define HAVE_MPI

/* #undef HAVE_MUELU_DEBUG */

/* #undef HAVE_MUELU_EXPLICIT_INSTANTIATION */

/* #undef HAVE_MUELU_PROFILING */

/* #undef HAVE_MUELU_GOOGLE_PERFTOOLS */

/* #undef HAVE_MUELU_EXPERIMENTAL */

/* Optional Dependencies */

#define HAVE_MUELU_AMESOS

#define HAVE_MUELU_AMESOS2

#define HAVE_MUELU_AZTECOO

#define HAVE_MUELU_BELOS

#define HAVE_MUELU_EPETRA

#define HAVE_MUELU_EPETRAEXT

#define HAVE_MUELU_GALERI

#define HAVE_MUELU_IFPACK

#define HAVE_MUELU_IFPACK2

#define HAVE_MUELU_KOKKOSCLASSIC

#define HAVE_MUELU_ML

#define HAVE_MUELU_TPETRA

#define HAVE_MUELU_STRATIMIKOS

#define HAVE_MUELU_ZOLTAN

/* #undef HAVE_MUELU_ZOLTAN2 */

/* Optional TPL */

/* #undef HAVE_MUELU_BOOST */
