
#define HAVE_MPI

#define HAVE_STRATIMIKOS_AMESOS

#define HAVE_STRATIMIKOS_AZTECOO

#define HAVE_STRATIMIKOS_BELOS

#define HAVE_STRATIMIKOS_EPETRAEXT

#define HAVE_STRATIMIKOS_IFPACK

#define HAVE_STRATIMIKOS_ML

#ifndef STRATIMIKOS_FUNC_TIME_MONITOR
#  define STRATIMIKOS_TEUCHOS_TIME_MONITOR
#  define STRATIMIKOS_FUNC_TIME_MONITOR(FUNCNAME) \
     TEUCHOS_FUNC_TIME_MONITOR_DIFF(FUNCNAME, STRATIMIKOS)
#  define STRATIMIKOS_FUNC_TIME_MONITOR_DIFF(FUNCNAME, DIFF) \
     TEUCHOS_FUNC_TIME_MONITOR_DIFF(FUNCNAME, DIFF)
#endif

