
#include "TrilinosPlatform_config.h"

#define TEUCHOS_ORDINAL_TYPE ptrdiff_t
#define TEUCHOS_LIB_DLL_EXPORT
#define HAVE_TEUCHOS_BLASFLOAT 
#define HAVE_TEUCHOS_COMM_TIMERS 
#define HAVE_TEUCHOS_COMPLEX 
#define HAVE_TEUCHOS_EXTENDED 

/* #define HAVE_TEUCHOS_EXPLICIT_INSTANTIATION */
