
#include "TrilinosPlatform_config.h"

#define HAVE_TEUCHOS_BLASFLOAT 

#define HAVE_TEUCHOS_COMM_TIMERS 

#define HAVE_TEUCHOS_COMPLEX 

#define HAVE_TEUCHOS_EXTENDED 

/* #define HAVE_TEUCHOS_EXPLICIT_INSTANTIATION */
