
/* #undef HAVE_THYRA_EPETRA */

/* #undef HAVE_THYRA_EPETRAEXT */

/* #undef HAVE_THYRA_TPETRA */

/* #undef HAVE_THYRA_TEUCHOS_BLASFLOAT */

#define HAVE_THYRA_FLOAT

#define HAVE_THYRA_COMPLEX

/* #undef HAVE_THYRA_DEBUG */

/* #undef HAVE_THYRA_EXPLICIT_INSTANTIATION */

#define HAVE_THYRA_ME_POLYNOMIAL

#ifndef THYRA_FUNC_TIME_MONITOR
#  define THYRA_TEUCHOS_TIME_MONITOR
#  define THYRA_FUNC_TIME_MONITOR(FUNCNAME) \
     TEUCHOS_FUNC_TIME_MONITOR_DIFF(FUNCNAME, THYRA)
#  define THYRA_FUNC_TIME_MONITOR_DIFF(FUNCNAME, DIFF) \
     TEUCHOS_FUNC_TIME_MONITOR_DIFF(FUNCNAME, DIFF)
#endif


#define THYRA_DEPRECATED
