#ifndef TPETRACORE_ETIHELPERMACROS_H
#define TPETRACORE_ETIHELPERMACROS_H

#include <Tpetra_ConfigDefs.hpp>

/* Tpetra provides official support for the following nodes */
#include <Kokkos_DefaultNode.hpp>

/* Tpetra provides official support for dd_real and qd_real */
#if defined(HAVE_TPETRA_QD)
#include <qd/qd_real.h>
#endif

#define TPETRA_INSTANTIATE_TSLGN(INSTMACRO)


#define TPETRA_INSTANTIATE_CONVERT(INSTMACRO)


#define TPETRA_INSTANTIATE_VECTOR(INSTMACRO)


#define TPETRA_INSTANTIATE_SLGN(INSTMACRO)


#define TPETRA_INSTANTIATE_PLGN(INSTMACRO)


#define TPETRA_INSTANTIATE_LGN(INSTMACRO)


#define TPETRA_INSTANTIATE_TSLG(INSTMACRO)


#define TPETRA_INSTANTIATE_SLG(INSTMACRO)


#define TPETRA_INSTANTIATE_LG(INSTMACRO)


#define TPETRA_INSTANTIATE_SL(INSTMACRO)


#define TPETRA_INSTANTIATE_N(INSTMACRO)


#define TPETRA_INSTANTIATE_SLGN_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_LGN_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_SLG_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_LG_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_N_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_TSLGN_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_TSLG_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_CONVERT_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_TESTMV(INSTMACRO)


#define TPETRA_INSTANTIATE_TESTMV_NOGPU(INSTMACRO)


#define TPETRA_INSTANTIATE_DOUBLE_INT_INT_N(INSTMACRO)


#define TPETRA_INSTANTIATE_SLGN_NO_ORDINAL_SCALAR(INSTMACRO)


#define TPETRA_INSTANTIATE_SLG_NO_ORDINAL_SCALAR(INSTMACRO)


#define TPETRA_ETI_MANGLING_TYPEDEFS() 

#endif // TPETRACORE_ETIHELPERMACROS_H
