SET(LIB_REQUIRED_DEP_PACKAGES Teuchos KokkosCore KokkosContainers Tpetra)
SET(LIB_OPTIONAL_DEP_PACKAGES Epetra EpetraExt KokkosKernels Thyra)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES Epetra EpetraExt Tpetra KokkosKernels Thyra)
SET(LIB_REQUIRED_DEP_TPLS BLAS LAPACK)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

#TODO: why there is no EXAMPLE_*_DEP_* ?
