SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES Teuchos Epetra Zoltan Galeri Amesos Ifpack AztecOO EpetraExt Isorropia)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS BLAS LAPACK)
SET(LIB_OPTIONAL_DEP_TPLS MPI METIS ParMETIS PETSC SuperLU MATLAB)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS METIS ParMETIS SuperLU)

IF (ML_STANDALONE_PACKAGE)
  TRIBITS_ALLOW_MISSING_EXTERNAL_PACKAGES(
    Teuchos Epetra Zoltan Galeri Amesos Ifpack AztecOO EpetraExt Isorropia)
ENDIF()
