set(CMAKE_GENERATOR "NMake Makefiles" CACHE STRING "")
set(CLAPACK_DIR "C:/trilinos_projects/clapack_build" CACHE FILEPATH "")
set(CMAKE_BUILD_TYPE "RELEASE" CACHE STRING "")
set(Boost_INCLUDE_DIRS "c:/trilinos_projects/boost_1_40_0" CACHE FILEPATH "")
set(TPL_ENABLE_Netcdf OFF CACHE BOOL "")
set( Trilinos_ENABLE_ALL_PACKAGES ON CACHE BOOL "" )
set( Trilinos_ENABLE_TESTS ON CACHE BOOL "" )
set( Trilinos_ENABLE_TrilinosFramework OFF CACHE BOOL "" )
set( Trilinos_ENABLE_Stokhos OFF CACHE BOOL "" )
set( Trilinos_ENABLE_Piro OFF CACHE BOOL "" )
set( Trilinos_ENABLE_FEApp OFF CACHE BOOL "" )
set( Trilinos_ENABLE_Thyra OFF CACHE BOOL "" )
set( Trilinos_ENABLE_ThyraCore OFF CACHE BOOL "" )
set( Trilinos_ENABLE_ThyraEpetraAdapters OFF CACHE BOOL "" )
set( Trilinos_ENABLE_ThyraEpetraExtAdapters OFF CACHE BOOL "" )
set( Trilinos_ENABLE_ThyraTpetraAdapters OFF CACHE BOOL "" )
