#include "ml_defs.h"

void MLFORTRAN(daxpy)(void );
void MLFORTRAN(dasum)(void );
void MLFORTRAN(dlamch)(void );
void MLFORTRAN(dgetrs)(void );
void MLFORTRAN(ddot)(void );
void MLFORTRAN(xerbla)(void );
void MLFORTRAN(dlaswp)(void );
void MLFORTRAN(dgemm)(void );
void MLFORTRAN(dtrsm)(void );
void MLFORTRAN(dgetf2)(void );
void MLFORTRAN(dswap)(void );
void MLFORTRAN(dger)(void );
void MLFORTRAN(dscal)(void );
void MLFORTRAN(idamax)(void );
void MLFORTRAN(dgeqr2)(void );
void MLFORTRAN(dlarfb)(void );
void MLFORTRAN(dlarft)(void );
void MLFORTRAN(dlarf)(void );
void MLFORTRAN(dlarfg)(void );
void MLFORTRAN(dgemv)(void );
void MLFORTRAN(dtrmv)(void );
void MLFORTRAN(dcopy)(void );
void MLFORTRAN(dtrmm)(void );
void MLFORTRAN(dlamc2)(void );
void MLFORTRAN(dlamc1)(void );
void MLFORTRAN(dlamc4)(void );
void MLFORTRAN(dlamc5)(void );
void MLFORTRAN(dorg2r)(void );
void MLFORTRAN(dgelq2)(void );
void MLFORTRAN(dlabad)(void );
void MLFORTRAN(dgelqf)(void );
void MLFORTRAN(dlascl)(void );
void MLFORTRAN(dgeqrf)(void );
void MLFORTRAN(dlaset)(void );
void MLFORTRAN(dormlq)(void );
void MLFORTRAN(dormqr)(void );
void MLFORTRAN(dlassq)(void );
void MLFORTRAN(dorm2r)(void );
void MLFORTRAN(dorml2)(void );
void MLFORTRAN(dtrsv)(void );
void MLFORTRAN(dgetrf)(void );
void MLFORTRAN(dpotrs)(void );
void MLFORTRAN(dgels)(void );
void MLFORTRAN(dorgqr)(void );
void MLFORTRAN(lsame)(void );
void MLFORTRAN(ilaenv)(void );
void MLFORTRAN(dlamc3)(void );
void MLFORTRAN(dlange)(void );
void MLFORTRAN(dnrm2)(void );
void MLFORTRAN(dlapy2)(void );
void MLFORTRAN(dlamch)(void );



int main(int argc, char *argv[]){
 MLFORTRAN(daxpy)();
 MLFORTRAN(dasum)();
 MLFORTRAN(dlamch)();
 MLFORTRAN(dgetrs)( );
 MLFORTRAN(ddot)( );
 MLFORTRAN(xerbla)( );
 MLFORTRAN(dlaswp)( );
 MLFORTRAN(dgemm)( );
 MLFORTRAN(dtrsm)( );
 MLFORTRAN(dgetf2)( );
 MLFORTRAN(dswap)( );
 MLFORTRAN(dger)( );
 MLFORTRAN(dscal)( );
 MLFORTRAN(idamax)( );
 MLFORTRAN(dgeqr2)( );
 MLFORTRAN(dlarfb)( );
 MLFORTRAN(dlarft)( );
 MLFORTRAN(dlarf)( );
 MLFORTRAN(dlarfg)( );
 MLFORTRAN(dgemv)( );
 MLFORTRAN(dtrmv)( );
 MLFORTRAN(dcopy)( );
 MLFORTRAN(dtrmm)( );
 MLFORTRAN(dlamc2)( );
 MLFORTRAN(dlamc1)( );
 MLFORTRAN(dlamc4)( );
 MLFORTRAN(dlamc5)( );
 MLFORTRAN(dorg2r)( );
 MLFORTRAN(dgelq2)( );
 MLFORTRAN(dlabad)( );
 MLFORTRAN(dgelqf)( );
 MLFORTRAN(dlascl)( );
 MLFORTRAN(dgeqrf)( );
 MLFORTRAN(dlaset)( );
 MLFORTRAN(dormlq)( );
 MLFORTRAN(dormqr)( );
 MLFORTRAN(dlassq)( );
 MLFORTRAN(dorm2r)( );
 MLFORTRAN(dorml2)( );
 MLFORTRAN(dtrsv)( );
 MLFORTRAN(dgetrf)( );
 MLFORTRAN(dpotrs)( );
 MLFORTRAN(dgels)( );
 MLFORTRAN(dorgqr)( );
 MLFORTRAN(lsame)( );
 MLFORTRAN(ilaenv)( );
 MLFORTRAN(dlamc3)( );
 MLFORTRAN(dlange)( );
 MLFORTRAN(dnrm2)( );
 MLFORTRAN(dlapy2)( );
 MLFORTRAN(dlamch)( );
  return 0;
}
