#ifdef USE_VENDOR_BLAS
#define ML_IDAMAX_FUNC
#define ML_DSWAP_FUNC
#define ML_DSCAL_FUNC
#define ML_DAXPY_FUNC
#define ML_DASUM_FUNC
#define ML_DDOT_FUNC
#define ML_DNRM2_FUNC
#define ML_DCOPY_FUNC
#define ML_DGEMM_FUNC
#define ML_DTRSM_FUNC
#define ML_DTRMM_FUNC
#endif

#ifdef USE_VENDOR_LAPACK

#define ML_DTRSV_FUNC
#define ML_DGETRF_FUNC
#define ML_DGETRS_FUNC
#define ML_XERBLA_FUNC
#define ML_LSAME_FUNC
#define ML_DLASWP_FUNC
#define ML_DGETF2_FUNC
#define ML_DGER_FUNC
#define ML_ILAENV_FUNC
#define ML_DGEMV_FUNC
#define ML_DTRMV_FUNC
#define ML_DLAMCH_FUNC
#define ML_DLAMC1_FUNC
#define ML_DLAMC2_FUNC
#define ML_DLAMC3_FUNC
#define ML_DLAMC4_FUNC
#define ML_DLAMC5_FUNC
#endif
