#ifndef XPETRA_EPETRAMULTIVECTOR_FWD_HPP
#define XPETRA_EPETRAMULTIVECTOR_FWD_HPP

namespace Xpetra {
  class EpetraMultiVector;
}

#ifndef XPETRA_EPETRAMULTIVECTOR_SHORT
#define XPETRA_EPETRAMULTIVECTOR_SHORT
#endif

#endif // XPETRA_EPETRAMULTIVECTOR_FWD_HPP
