#ifndef XPETRA_DEFAULTPLATFORM_FWD_HPP
#define XPETRA_DEFAULTPLATFORM_FWD_HPP

namespace Xpetra {
  class DefaultPlatform;
}

#ifndef XPETRA_DEFAULTPLATFORM_SHORT
#define XPETRA_DEFAULTPLATFORM_SHORT
#endif

#endif // XPETRA_DEFAULTPLATFORM_FWD_HPP
