#ifndef XPETRA_EPETRAIMPORT_FWD_HPP
#define XPETRA_EPETRAIMPORT_FWD_HPP

namespace Xpetra {
  class EpetraImport;
}

#ifndef XPETRA_EPETRAIMPORT_SHORT
#define XPETRA_EPETRAIMPORT_SHORT
#endif

#endif // XPETRA_EPETRAIMPORT_FWD_HPP
