SET(LIB_REQUIRED_DEP_PACKAGES Anasazi Belos Zoltan2Core)
SET(LIB_OPTIONAL_DEP_PACKAGES MueLu)
SET(TEST_REQUIRED_DEP_PACKAGES Anasazi Belos Zoltan2Core)
SET(TEST_OPTIONAL_DEP_PACKAGES MueLu)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS) 
SET(TEST_OPTIONAL_DEP_TPLS)

