SET(LIB_REQUIRED_DEP_PACKAGES Anasazi Belos Ifpack2 Zoltan2Core)
SET(LIB_OPTIONAL_DEP_PACKAGES MueLu Galeri)
SET(TEST_REQUIRED_DEP_PACKAGES Anasazi Belos Ifpack2 Zoltan2Core)
SET(TEST_OPTIONAL_DEP_PACKAGES MueLu Galeri)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS) 
SET(TEST_OPTIONAL_DEP_TPLS)

