if( ROL_ENABLE_ColoredConfig )

string(ASCII 27 Esc)
set(ColorReset  "${Esc}[m")
set(ColorBold   "${Esc}[1m")
set(Red         "${Esc}[31m")
set(Green       "${Esc}[32m")
set(Yellow      "${Esc}[33m")
set(Blue        "${Esc}[34m")
set(Magenta     "${Esc}[35m")
set(Cyan        "${Esc}[36m")
set(White       "${Esc}[37m")
set(BoldRed     "${Esc}[1;31m")
set(BoldGreen   "${Esc}[1;32m")
set(BoldYellow  "${Esc}[1;33m")
set(BoldBlue    "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan    "${Esc}[1;36m")
set(BoldWhite   "${Esc}[1;37m")

else()
set(ColorReset  "")
set(ColorBold   "")
set(Red         "")
set(Green       "")
set(Yellow      "")
set(Blue        "")
set(Magenta     "")
set(Cyan        "")
set(White       "")
set(BoldRed     "")
set(BoldGreen   "")
set(BoldYellow  "")
set(BoldBlue    "")
set(BoldMagenta "")
set(BoldCyan    "")
set(BoldWhite   "")
endif()

function(red TEXT)
  message("${Red}${TEXT}${ColorReset}")
endfunction()

function(green TEXT)
  message("${Green}${TEXT}${ColorReset}")
endfunction()

function(yellow TEXT)
  message("${Yellow}${TEXT}${ColorReset}")
endfunction()

function(blue TEXT)
  message("${Blue}${TEXT}${ColorReset}")
endfunction()

function(magenta TEXT)
  message("${Magenta}${TEXT}${ColorReset}")
endfunction()

function(cyan TEXT)
  message("${Cyan}${TEXT}${ColorReset}")
endfunction()

function(white TEXT)
  message("${White}${TEXT}${ColorReset}")
endfunction()

function(bold_red TEXT)
  message("${BoldRed}${TEXT}${ColorReset}")
endfunction()

function(bold_green TEXT)
  message("${BoldGreen}${TEXT}${ColorReset}")
endfunction()

function(bold_yellow TEXT)
  message("${BoldYellow}${TEXT}${ColorReset}")
endfunction()

function(bold_blue TEXT)
  message("${BoldBlue}${TEXT}${ColorReset}")
endfunction()

function(bold_magenta TEXT)
  message("${BoldMagenta}${TEXT}${ColorReset}")
endfunction()

function(bold_cyan TEXT)
  message("${BoldCyan}${TEXT}${ColorReset}")
endfunction()

function(bold_white TEXT)
  message("${BoldWhite}${TEXT}${ColorReset}")
endfunction()

