#ifndef MUELU_TWOLEVELFACTORYBASE_FWD_HPP
#define MUELU_TWOLEVELFACTORYBASE_FWD_HPP

namespace MueLu {
  class TwoLevelFactoryBase;
}

#ifndef MUELU_TWOLEVELFACTORYBASE_SHORT
#define MUELU_TWOLEVELFACTORYBASE_SHORT
#endif

#endif // MUELU_TWOLEVELFACTORYBASE_FWD_HPP
