#ifndef MUELU_LEFTOVERAGGREGATIONALGORITHM_FWD_HPP
#define MUELU_LEFTOVERAGGREGATIONALGORITHM_FWD_HPP

namespace MueLu {
  template <class LocalOrdinal, class GlobalOrdinal, class Node, class LocalMatOps>
  class LeftoverAggregationAlgorithm;
}

#ifndef MUELU_LEFTOVERAGGREGATIONALGORITHM_SHORT
#define MUELU_LEFTOVERAGGREGATIONALGORITHM_SHORT
#endif

#endif // MUELU_LEFTOVERAGGREGATIONALGORITHM_FWD_HPP
