#ifndef MUELU_SMOOTHERFACTORYBASE_FWD_HPP
#define MUELU_SMOOTHERFACTORYBASE_FWD_HPP

namespace MueLu {
  class SmootherFactoryBase;
}

#ifndef MUELU_SMOOTHERFACTORYBASE_SHORT
#define MUELU_SMOOTHERFACTORYBASE_SHORT
#endif

#endif // MUELU_SMOOTHERFACTORYBASE_FWD_HPP
