#ifndef MUELU_FACTORYMANAGERBASE_FWD_HPP
#define MUELU_FACTORYMANAGERBASE_FWD_HPP

namespace MueLu {
  class FactoryManagerBase;
}

#ifndef MUELU_FACTORYMANAGERBASE_SHORT
#define MUELU_FACTORYMANAGERBASE_SHORT
#endif

#endif // MUELU_FACTORYMANAGERBASE_FWD_HPP
