#ifndef MUELU_SINGLELEVELFACTORYBASE_FWD_HPP
#define MUELU_SINGLELEVELFACTORYBASE_FWD_HPP

namespace MueLu {
  class SingleLevelFactoryBase;
}

#ifndef MUELU_SINGLELEVELFACTORYBASE_SHORT
#define MUELU_SINGLELEVELFACTORYBASE_SHORT
#endif

#endif // MUELU_SINGLELEVELFACTORYBASE_FWD_HPP
