SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES Amesos AztecOO Belos EpetraExt Ifpack Isorropia ML MueLu NOX Stokhos Zoltan)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES Amesos AvatarT AztecOO Epetra EpetraExt Ifpack Intrepid Intrepid2 Isorropia KokkosContainers KokkosCore KokkosKernels ML MueLu MueLu Pamgen SEACASExodus SEACASNemesis Sacado STKIO STKMesh Stokhos Stratimikos Teko TeuchosKokkosComm TeuchosKokkosCompat Tpetra TriKota Zoltan)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS Avatar TASMANIAN)
