#!/bin/sh

echo " "
echo "Running Petra_ESI unit-tests..."
echo " "

test_failed=0

mpi_tests=`ls *.MPI.x`
np=2

for test_exe in ${mpi_tests};\
do
  echo "running test    ${test_exe}  on ${np} processors..."

  result="PASSED"

  (./run.mpi ${np} ${test_exe})
  if [ ${?} != 0 ] ; then \
     result="FAILED";\
     test_failed=1;\
  fi

  echo "             ******** test    ${test_exe}   ${result} ********"
  echo " "
done

ser_tests=`ls *.SERIAL.x`

for test_exe in ${ser_tests};\
do
  echo "running test    ${test_exe}..."

  result="PASSED"

  (${test_exe})
  if [ ${?} != 0 ] ; then \
     result="FAILED";\
     test_failed=1;\
  fi

  echo "             ******** test    ${test_exe}   ${result} ********"
  echo " "
done

if [ ${test_failed} != 0 ] ; then \
  echo "one or more tests failed.";\
  echo " ";\
  exit 1;\
else \
  echo "all tests passed.";\
  echo " ";\
  exit 0;\
fi

