include(CMakeFindDependencyMacro)
find_dependency(Kokkos REQUIRED)
find_dependency(Shards REQUIRED)
find_dependency(MPI REQUIRED)
find_dependency(ArborX QUIET)
include("${CMAKE_CURRENT_LIST_DIR}/stkLapack.cmake")
find_dependency(SEACAS REQUIRED)
find_dependency(GTest REQUIRED)
find_dependency(Zoltan2Core REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/stkTargets.cmake")
