if(CMAKE_PROJECT_NAME STREQUAL "Seacas" OR CMAKE_PROJECT_NAME STREQUAL "SEACAS" )
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_TPLS fmt
  LIB_OPTIONAL_PACKAGES SEACASExodus
  TEST_OPTIONAL_TPLS Pthread
)
else()
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_OPTIONAL_PACKAGES SEACASExodus
  TEST_OPTIONAL_TPLS Pthread
)
endif()
