      SUBROUTINE SORBLK (IDELB, INDEX, MAT, NELBLK)
      DIMENSION IDELB(*), INDEX(*), MAT(6,*)
C
      CALL INDEXI (IDELB, INDEX, NELBLK, .TRUE.)
      DO 10 I=1, NELBLK
         MAT(6,I) = INDEX(I)
   10 CONTINUE
      RETURN
      END
