MESSAGE(STATUS "${PACKAGE_NAME}: Processing ETI / test support")

IF(NOX_ENABLE_ABSTRACT_IMPLEMENTATION_TPETRA)
  
  # Create the NOX_Tpetra_ETIHelperMacros.hpp file.
  SET(NOX_TPETRA_ETI_FIELDS "S|LO|GO|N")

  LIST(JOIN NOX_TPETRA_ETI_SCALARS "|" NOX_TPETRA_ETI_SCALARS)
  LIST(JOIN NOX_TPETRA_ETI_LORDS   "|" NOX_TPETRA_ETI_LORDS)
  LIST(JOIN NOX_TPETRA_ETI_GORDS   "|" NOX_TPETRA_ETI_GORDS)
  LIST(JOIN NOX_TPETRA_ETI_NODES   "|" NOX_TPETRA_ETI_NODES)

  TRIBITS_ETI_TYPE_EXPANSION(NOX_TPETRA_ETI_LIBRARYSET
    "S=${NOX_TPETRA_ETI_SCALARS}" 
    "LO=${NOX_TPETRA_ETI_LORDS}" 
    "GO=${NOX_TPETRA_ETI_GORDS}"
    "N=${NOX_TPETRA_ETI_NODES}"
  )

  TRIBITS_ETI_GENERATE_MACROS(
    "${NOX_TPETRA_ETI_FIELDS}"
    "${NOX_TPETRA_ETI_LIBRARYSET}"
    ""  
    list_of_manglings eti_typedefs
    "NOX_TPETRA_INSTANTIATE_SLGN(S,LO,GO,N)" NOX_TPETRA_ETIMACRO_SLGN                          
  )

  CONFIGURE_FILE(${NOX_SOURCE_DIR}/cmake/NOX_Tpetra_ETIHelperMacros.hpp.in ${NOX_BINARY_DIR}/src/NOX_Tpetra_ETIHelperMacros.hpp)

ENDIF()