INCLUDE(AppendCmndlineArgs)
INCLUDE(DualScopeSet)

MACRO(DUAL_SCOPE_APPEND_CMNDLINE_ARGS  CMNDLINE_VAR_NAME  EXTRAARGS)
  APPEND_CMNDLINE_ARGS(${CMNDLINE_VAR_NAME} "${EXTRAARGS}")
  SET(${CMNDLINE_VAR_NAME} "${${CMNDLINE_VAR_NAME}}" PARENT_SCOPE)
ENDMACRO()
