INCLUDE(PrependCmndlineArgs)
INCLUDE(DualScopeSet)

MACRO(DUAL_SCOPE_PREPEND_CMNDLINE_ARGS  CMNDLINE_VAR_NAME  EXTRAARGS)
  PREPEND_CMNDLINE_ARGS(${CMNDLINE_VAR_NAME} "${EXTRAARGS}")
  SET(${CMNDLINE_VAR_NAME} "${${CMNDLINE_VAR_NAME}}" PARENT_SCOPE)
ENDMACRO()
