
#
# Generate a script file given a script body string and a set of optional
# file dependencies
#

MACRO(GENERATE_SCRIPT_FILE_TARGET SCRIPT_FILE_NAME SCRIPT_BODY)

  #MESSAGE("\nGENERATE_SCRIPT_FILE_TARGET:
  #SCRIPT_FILE_NAME = ${SCRIPT_FILE_NAME}
  #${SCRIPT_BODY}"
  #)
  
  SET(TEST_SCRIPT_FILE "${CMAKE_CURRENT_BINARY_DIR}/${SCRIPT_FILE_NAME}")

  SET(TEST_SCRIPT_FILE_TMP "${TEST_SCRIPT_FILE}.tmp")

  FILE(WRITE ${TEST_SCRIPT_FILE_TMP} "${SCRIPT_BODY}")

  ADD_CUSTOM_COMMAND(
    OUTPUT ${SCRIPT_FILE_NAME}
    DEPENDS ${TEST_SCRIPT_FILE_TMP}
    DEPENDS ${ARGN}
    COMMAND cp ARGS ${TEST_SCRIPT_FILE_TMP} ${SCRIPT_FILE_NAME}
    COMMAND chmod ARGS a+x ${SCRIPT_FILE_NAME}
    )

  SET(CMAKE_EXECUTABLE_SUFFIX "")

  ADD_CUSTOM_TARGET( ${SCRIPT_FILE_NAME}-target ALL
    DEPENDS ${SCRIPT_FILE_NAME} )

ENDMACRO()
