

FUNCTION(JOIN OUTPUT_STRING_VAR SEP_STR)
  SET(OUTPUT_STRING "")
  FOREACH(STRING_VAL ${ARGN})
    SET(OUTPUT_STRING "${OUTPUT_STRING}${SEP_STR}${STRING_VAL}")
  ENDFOREACH()
  SET(${OUTPUT_STRING_VAR} "${OUTPUT_STRING}" PARENT_SCOPE)
ENDFUNCTION()
