INCLUDE(AssertDefined)


FUNCTION(PRINT_NONEMPTY_VAR VARIBLE_NAME)
  ASSERT_DEFINED(VARIBLE_NAME)
  IF (NOT "${${VARIBLE_NAME}}" STREQUAL "")
    MESSAGE(STATUS "${VARIBLE_NAME}='${${VARIBLE_NAME}}'")
  ENDIF()
ENDFUNCTION()
