
FUNCTION(SPLIT  INPUT_STRING  SEP_STR  OUTPUT_STRING_VAR)
  STRING(REGEX REPLACE "${SEP_STR}" ";" OUTPUT_STRING "${INPUT_STRING}")
  SET(${OUTPUT_STRING_VAR} "${OUTPUT_STRING}" PARENT_SCOPE)
ENDFUNCTION()
