# .bash_profile
# echo bash_profile: path is $PATH
# echo bash_profile: git is `which git`
PATH=${PATH}:/usr/local/git/bin; export PATH

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

unset USERNAME

export CVS_RSH=ssh

# User specific environment and startup programs
