MACRO(TRIBITS_REPOSITORY_DEFINE_PACKAGING)

  ASSERT_DEFINED(${REPOSITORY_NAME}_SOURCE_DIR)
  APPEND_SET(CPACK_SOURCE_IGNORE_FILES
    "${${REPOSITORY_NAME}_SOURCE_DIR}/cmake/ctest/"
    )

ENDMACRO()
