# Options not specified by configure will be defined as ON
FUNCTION( ENABLE_BY_DEFAULT OPTION_NAME )
  IF( NOT DEFINED ${PACKAGE_NAME}_ENABLE_${OPTION_NAME} )
    MESSAGE( "${PACKAGE_NAME}_ENABLE_${OPTION_NAME} is not defined")
    MESSAGE( "Setting to default value = ON" )
    SET( ${PACKAGE_NAME}_ENABLE_${OPTION_NAME} ON )
  ENDIF()
ENDFUNCTION()

# Options not specified by configure will be defined as OFF
FUNCTION( DISABLE_BY_DEFAULT OPTION_NAME )
  IF( NOT DEFINED ${PACKAGE_NAME}_ENABLE_${OPTION_NAME} )
    MESSAGE( "${PACKAGE_NAME}_ENABLE_${OPTION_NAME} is not defined")
    MESSAGE( "Setting to default value = OFF" )
    SET( ${PACKAGE_NAME}_ENABLE_${OPTION_NAME} OFF )
  ENDIF()
ENDFUNCTION()

#ENABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_TEUCHOS )
#DISABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_STD_SHARED_PTR )
#DISABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_BOOST_PROPERTY_TREE )


# Will add the subdirectory if set to ON
FUNCTION( ADD_SUBDIRECTORY_IF DIR CONDITION ) 
  SET(${CONDITION} ${${CONDITION}} PARENT_SCOPE)
  IF( ${${CONDITION}} )
    ADD_SUBDIRECTORY(${DIR})
  ENDIF()
ENDFUNCTION() 


# WILL ADD THE SUBDIRECTORY IF THE PARAMETER IS SET TO OFF
FUNCTION( ADD_SUBDIRECTORY_IF_OFF DIR CONDITION )
  SET(${CONDITION} ${${CONDITION}} PARENT_SCOPE)
  IF( NOT ${${CONDITION}} )
    ADD_SUBDIRECTORY(${DIR})
  ENDIF()
ENDFUNCTION()

# Include directory and headers within if CONDITION=ON
FUNCTION( INCLUDE_DIRECTORY_IF DIR HEADERS CONDITION ) 
  SET( ${HEADERS} ${${HEADERS}} PARENT_SCOPE )
  SET( ${CONDITION} ${${CONDITION}} PARENT_SCOPE )
  IF( ${CONDITION} )
    MESSAGE( "Conditional include (${CONDITION}=${${CONDITION}})")
    MESSAGE( "Including directories ${DIR} " )
    INCLUDE_DIRECTORIES(${DIR})
    APPEND_GLOB(HEADER ${DIR}/*.hpp)
  ENDIF( ${CONDITION} )
ENDFUNCTION() 

FUNCTION( INCLUDE_DIRECTORY_IF_OFF DIR HEADERS CONDITION ) 
  SET( ${HEADERS} ${${HEADERS}} PARENT_SCOPE )
  SET( ${CONDITION} ${${CONDITION}} PARENT_SCOPE )
  IF( NOT ${CONDITION} )
    MESSAGE( "Conditional include (${CONDITION}=${${CONDITION}})")
    MESSAGE( "Including directories ${DIR} " )
    INCLUDE_DIRECTORIES(${DIR})
    APPEND_GLOB(HEADERS ${DIR}/*.hpp)
  ENDIF( NOT ${CONDITION} )
  INCLUDE_DIRECTORIES(${DIR})
  APPEND_GLOB(HEADERS ${DIR}/*.hpp)
ENDFUNCTION()



