INCLUDE(BuildOptionFunctions)

# Set default options
ENABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_TEUCHOS_PARAMETERLIST )
ENABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_TEUCHOS_RCP )
DISABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_STD_SHARED_PTR )
DISABLE_BY_DEFAULT( ${PACKAGE_NAME}_ENABLE_BOOST_PROPERTY_TREE )

# If Teuchos option is enabled, disable alternative option



SET_PROPERTY( GLOBAL PROPERTY ROL_TEUCHOS_PARAMETERLIST "Teuchos::ParameterList" )
SET_PROPERTY( GLOBAL PROPERTY ROL_TEUCHOS_RCP           "Teuchos::RCP"           )
SET_PROPERTY( GLOBAL PROPERTY ROL_BOOST_PROPERTY_TREE   "boost::property_tree"   )
SET_PROPERTY( GLOBAL PROPERTY ROL_STD_SHARED_PTR        "std::shared_ptr"        )

# Compatibility Directory 
SET( DIR ${${PACKAGE_NAME}_SOURCE_DIR}/src/compatibility )

# Override if specified
IF( ${PACKAGE_NAME}_ENABLE_STD_SHARED_PTR ) 
  SET_PROPERTY( GLOBAL PROPERTY ROL_PTR     "std::shared_ptr"       )
  SET_PROPERTY( GLOBAL PROPERTY ROL_PTR_DIR "${DIR}/std/shared_ptr" )
ELSE()
  SET_PROPERTY( GLOBAL PROPERTY ROL_PTR     "Teuchos::RCP"       )
  SET_PROPERTY( GLOBAL PROPERTY ROL_PTR_DIR "${DIR}/teuchos/rcp" )
ENDIF()

IF( ${PACKAGE_NAME}_ENABLE_BOOST_PROPERTY_TREE ) 
  SET_PROPERTY( GLOBAL PROPERTY ROL_PARAMETERLIST     "boost::property_tree"       )
  SET_PROPERTY( GLOBAL PROPERTY ROL_PARAMETERLIST_DIR "${DIR}/boost/property_tree" )
ELSE()
  SET_PROPERTY( GLOBAL PROPERTY ROL_PARAMETERLIST     "Teuchos::ParameterList"       )
  SET_PROPERTY( GLOBAL PROPERTY ROL_PARAMETERLIST_DIR "${DIR}/teuchos/parameterlist" )
ENDIF()



