
FUNCTION( ADD_ADAPTER ADAPTER )
  IF( ${${PACKAGE_NAME}_ENABLE_${ADAPTER}} )
    STRING( TOLOWER ${ADAPTER} ADAPTER_DIR )
    ADD_SUBDIRECTORY( ${${PACKAGE_NAME}_SOURCE_DIR}/adapters/${ADAPTER_DIR} )
  ENDIF()
ENDFUNCTION()

FUNCTION( SET_DEFAULT OPTION_NAME DEFAULT_VALUE )
  IF( NOT DEFINED OPTION_NAME )
    SET( OPTION_NAME ${DEFAULT_VALUE} )
  ENDIF()
ENDFUNCTION()

# Options not specified by configure will be defined as ON
FUNCTION( ENABLE_BY_DEFAULT OPTION_NAME )
  IF( NOT DEFINED ${OPTION_NAME} )
    SET( ${OPTION_NAME} ON )
  ENDIF()
  SET( ${OPTION_NAME} ${${OPTION_NAME}} PARENT_SCOPE )
ENDFUNCTION()

# Options not specified by configure will be defined as OFF
FUNCTION( DISABLE_BY_DEFAULT OPTION_NAME )
  IF( NOT DEFINED ${OPTION_NAME} )
    SET( ${OPTION_NAME} OFF )
  ENDIF()
  SET( ${OPTION_NAME} ${${OPTION_NAME}} PARENT_SCOPE )
ENDFUNCTION()


