string(ASCII 27 Esc)

if(WIN32)
  set(ColorReset  "")
  set(ColorBold   "")
  set(Red         "")
  set(Green       "")
  set(Yellow      "")
  set(Blue        "")
  set(Magenta     "")
  set(Cyan        "")
  set(White       "")
  set(BoldRed     "")
  set(BoldGreen   "")
  set(BoldYellow  "")
  set(BoldBlue    "")
  set(BoldMagenta "")
  set(BoldCyan    "")
  set(BoldWhite   "")
else()
  set(ColorReset  "${Esc}[m")
  set(ColorBold   "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()
