#SET(SUBPACKAGES_DIRS_CLASSIFICATION_OPTREQS
  # SubPackageName       Directory       Class       Req/Opt
#  xrol                   experimental    EX          OPTIONAL
#)      

IF(TPL_ENABLE_GTest)
  set(MAYBE_GTEST_TPL GTest)
  set(MAYBE_GTEST_PACKAGE)
ELSE()
  set(MAYBE_GTEST_TPL)
  set(MAYBE_GTEST_PACKAGE Gtest)
ENDIF()

SET(LIB_REQUIRED_DEP_PACKAGES Teuchos)
SET(LIB_OPTIONAL_DEP_PACKAGES Belos Epetra Tpetra Thyra Sacado Intrepid MiniTensor Shards Amesos Amesos2 Ifpack2 MueLu TriKota Tempus)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES ${MAYBE_GTEST_PACKAGE})
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS Boost ArrayFireCPU Eigen pebbl)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS ${MAYBE_GTEST_TPL})

