MACRO(PyROL_MAKE_TEST TEST_NAME)

  FILE(COPY ${CMAKE_CURRENT_SOURCE_DIR}/${TEST_NAME}.py DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

  TRIBITS_ADD_TEST(
    ${PYTHON_EXECUTABLE}
    NOEXEPREFIX
    NOEXESUFFIX
    NAME ${TEST_NAME}
    ARGS "${TEST_NAME}.py"
    PASS_REGULAR_EXPRESSION "OK"
    ${ARGN}
    )

  tribits_set_tests_properties(PyROL_${TEST_NAME}
    PROPERTIES ENVIRONMENT "${PyROL_PYTHONPATH}")

ENDMACRO(PyROL_MAKE_TEST TEST_NAME)
