MACRO(PYTHON_ADD_TEST TEST_NAME)

  TRIBITS_ADD_TEST(
    ${PYTHON_EXECUTABLE}
    NOEXEPREFIX
    NOEXESUFFIX
    NAME PYTHON_${TEST_NAME}
    ARGS "-m unittest ${TEST_NAME}.py"
    PASS_REGULAR_EXPRESSION "OK"
    ${ARGN}
    )

  tribits_set_tests_properties(ROL_PYTHON_${TEST_NAME}
    PROPERTIES ENVIRONMENT "${PyROL_PYTHONPATH}")

ENDMACRO(PYTHON_ADD_TEST TEST_NAME)
