SET(Trilinos_VERSION "10.3d")
SET(Trilinos_MAJOR_VERSION "10")
SET(Trilinos_MAJOR_MINOR_VERSION "100300")
SET(Trilinos_VERSION_STRING "10.3 (Dev)")

#this is for our testing scripts and should not be used elsewhere
SET(Trilinos_REPOSITORY_BRANCH "master" CACHE INTERNAL "")
SET(Trilinos_TESTING_TRACK "" CACHE INTERNAL "")


SET(TRILINOS_MAJOR_VERSION TRUE)
SET(TRILINOS_MAJOR_MINOR_VERSION TRUE)
SET(TRILINOS_VERSION_STRING TRUE)
