INCLUDE(Global_Set)

MACRO(TRILINOS_ADD_OPTION USER_OPTION_NAME MACRO_DEFINE_NAME DOCSTRING DEFAULT_VALUE)
  #MESSAGE("TRILINOS_ADD_OPTION: '${USER_OPTION_NAME}' '${MACRO_DEFINE_NAME}' '${DEFAULT_VALUE}'")
  SET( ${USER_OPTION_NAME} ${DEFAULT_VALUE} CACHE BOOL ${DOCSTRING} )
  IF(NOT ${MACRO_DEFINE_NAME} STREQUAL "")
    IF(${USER_OPTION_NAME})
      GLOBAL_SET(${MACRO_DEFINE_NAME} ON)
    ELSE()
      GLOBAL_SET(${MACRO_DEFINE_NAME} OFF)
    ENDIF()
  ENDIF()
ENDMACRO()

# 2008/10/05: rabartl: ToDo: Add an option to automatically add the macro
# define to any XXX_config.h file that gets configured by
# TRILINOS_PACKAGE_CONFIGURE_FILE(...).  This will help to eliminate
# duplication.
