if($ENV{CCACHE_NODISABLE})
  find_program(CCACHE_PROGRAM ccache)
  if(CCACHE_PROGRAM)
      if(CMAKE_GENERATOR STREQUAL "Xcode")
        message(FATAL_ERROR "ccache not supported with Xcode in Trilinos")
      else()
        set(CMAKE_C_COMPILER_LAUNCHER   "${CCACHE_PROGRAM}")
        set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
      endif()
  else()
      message(FATAL_ERROR "ccache requested but not found")
  endif()
endif()
