#!/bin/sh
../configure \
--with-install="/usr/bin/install -p" \
CXX=g++ \
CXXFLAGS="-ansi -pedantic -Wall -g -O0" \
CC=gcc \
F77=g77 \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-complex \
--enable-thyra \
--enable-epetra --enable-epetra-thyra 

#--enable-teuchos-gmp --with-incdir="/usr/local/include" --with-ldflags="-lgmp -lgmpxx" \
# Note: TSFExtended is enabled to make sure I don't break Kevin's code
# Note: Sundance needs TSF enabled!
# Note: Can not use --with-cppflags etc. since these are used *before* the standard C++ flags (CPPFLAGS)!
# ToDo: Turn back on -ansi once makefile is fixed!
