SET(LIB_REQUIRED_DEP_PACKAGES   Teuchos Stratimikos ThyraCore Tpetra Teko)
SET(LIB_OPTIONAL_DEP_PACKAGES   NOX Tempus Stokhos
    ROL Ifpack2 MueLu ThyraEpetraAdapters ThyraEpetraExtAdapters Epetra EpetraExt)
SET(TEST_REQUIRED_DEP_PACKAGES ThyraTpetraAdapters MPI)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS )
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
