# Can make Epetra & EpetraExt Optional in the future
SET(LIB_REQUIRED_DEP_PACKAGES   Teuchos ThyraCore ThyraEpetraAdapters ThyraEpetraExtAdapters Epetra EpetraExt)
SET(LIB_OPTIONAL_DEP_PACKAGES   NOX Rythmos MOOCHO Stokhos OptiPack TriKota)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS )
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
