name: AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

# Cancels any in progress 'workflows' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# actions: write needed by skip-duplicate-actions (handled below as per OpenSSF scorecard)
permissions:
  contents: read

jobs:
  # Jobs depend on the output of pre-checks to run.
  # Cancels new workflows if prior runs were successful (same tree hash)
  pre-checks:
        runs-on: ubuntu-latest
        # actions: write needed by skip-duplicate-actions
        permissions:
          actions: write
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
          with:
            skip_after_successful_duplicate: 'true'

  gcc12-openmpi4:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'gcc-12.3.0-openmpi-4.1.6', '20260507']"
      genconfig-string: "rhel8_gcc-openmpi_debug_shared_no-kokkos-arch_no-asan_complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-gcc-12.3.0-openmpi-4.1.6:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_debug_shared
      max-cores-allowed: 29
      num-concurrent-tests: 16

  clang19-openmpi4:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'clang-19.1.7-openmpi-4.1.6', '20260507']"
      genconfig-string: "rhel_clang-openmpi_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi9-clang-19.1.7-openmpi-4.1.6:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release-debug_shared
      max-cores-allowed: 29
      num-concurrent-tests: 16

  cuda12:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'cuda-12.4.1-gcc-12.3.0-openmpi-4.1.6', '20260507', 'gpu:A100']"
      genconfig-string: "rhel_cuda-12-gcc-openmpi_release_static_Ampere80_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-cuda-12.4.1-gcc-12.3.0-openmpi-4.1.6:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release_static
      max-cores-allowed: 56
      num-concurrent-tests: 112
      slots-per-gpu: 8

  gcc14:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'gcc-14', '20260507']"
      genconfig-string: "rhel_gcc_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi10-gcc-14:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release-debug_shared
      max-cores-allowed: 29
      num-concurrent-tests: 16

  cuda12-uvm:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'cuda-12.4.1-gcc-12.3.0-openmpi-4.1.6', '20260507']"
      genconfig-string: "rhel_cuda-gcc-openmpi_release_static_Ampere80_no-asan_complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-cuda-12.4.1-gcc-12.3.0-openmpi-4.1.6:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release_static_uvm
      max-cores-allowed: 56
      skip-run-tests: true

  oneapi2024:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'oneapi-2024.2', '20260507']"
      genconfig-string: "rhel_oneapi-intelmpi_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi9-oneapi-2024.2:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release-debug_shared
      max-cores-allowed: 29
      num-concurrent-tests: 16

  openmp:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'gcc-12.3.0-openmpi-4.1.6', '20260507']"
      genconfig-string: "rhel8_gcc-openmpi-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-gcc-12.3.0-openmpi-4.1.6:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release-debug_static_openmp
      max-cores-allowed: 29
      num-concurrent-tests: 16

  framework-tests:
    needs: pre-checks
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'python-3.9', '20260507']"
      genconfig-string: "rhel8_python_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-python-3.9:20260507
      cdash-track: "Pull Request"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_framework-tests
      skip-create-packageenables: true

  ramses-openmp:
    needs: [pre-checks, gcc12-openmpi4, openmp]
    if: ${{ !cancelled() && needs.pre-checks.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci.yml
    with:
      target-runner-labels: "['self-hosted', 'gcc-12.3.0-openmpi-4.1.6', '20260507']"
      genconfig-string: "rhel8_gcc-openmpi-openmp_release_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_ramses"
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/production/ubi8-gcc-12.3.0-openmpi-4.1.6:20260507
      cdash-track: "Pull Request (Non-blocking)"
      dashboard-build-name: PR-${{ github.event.pull_request.number }}_${AT2_IMAGE}_release_static_RAMSES
      max-cores-allowed: 29
      num-concurrent-tests: 16
      skip-create-packageenables: true
      extra-pr-driver-args: --extra-configure-args=-C;${GITHUB_WORKSPACE}/packages/framework/cmake-fragments/ramses/gcc-mpi-openmp.cmake

