name: C/C++ CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      TRILINOS_SRC_DIR: /home/runner/work/Trilinos/Trilinos
      TRILINOS_BUILD_DIR: /home/runner/work/Trilinos/Trilinos/build
    
    steps:
    - uses: actions/checkout@v3
    - name: PWD
      run: pwd
    - name: instal MPI
      run: sudo apt-get install libopenmpi-dev
    - name: enviroment variables
      run: env
    - name: mkdir build
      run: |
        mkdir build
    - name: ls
      run: ls
    - name: Build CMake
      working-directory: build
      run: sudo cmake -DTPL_ENABLE_MPI=ON -DTrilinos_ENABLE_Kokkos=ON -DCMAKE_INSTALL_PREFIX=$TRILINOS_BUILD_DIR $TRILINOS_SRC_DIR
    - name: dump build contents
      run: ls -R build
    - name: build 
      working-directory: build
      run: sudo make -j1
