name: C/C++ CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      TRILINOS_SRC_DIR: /home/runner/work/Trilinos/Trilinos
    
    steps:
    - uses: actions/checkout@v3
    - name: PWD
      run: pwd
    - name: enviroment variables
      run: env
    - name: mkdir build
      run: |
        mkdir build
    - name: ls
      run: ls
    - name: Build CMake
      working-directory: build
      run: sudo cmake -D CMAKE_BUILD_TYPE=DEBUG -D Trilinos_ENABLE_TESTS=ON "$@" $TRILINOS_SRC_DIR
    - name: dump build contents
      run: ls -R build
    - name: build 
      working-directory: build
      run: make -j1
