name: Flag PRs to master by adding the AT WIP keyword 
# Unless you are the autotester, of course

on:
  pull_request:
    types: [opened]
    branches: [master]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pull-requests: write
  
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add label
      uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3     
      if: "!contains(github.event.sender.login,'trilinos-autotester')"
      with:
        labels: "AT: WIP"     
    - name: Add comment
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      if: "!contains(github.event.sender.login,'trilinos-autotester')"
      with:
         message: |
            You seem to have created a PR on master.  This is not allowed behavior, so we've blocked your PR.  Please switch your PR to target the develop branch and remove the AT: WIP label.
      
