name: Update ROL Parameters

on:
  push:
    branches:
      - develop

jobs:
  update-parameters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        chmod +x find_parameters.sh

    - name: Run rol_parameters script
      run: python rol_parameters.py .

    # Uncomment and modify the following step if you want to move the file to a specific directory
    # - name: Move XML file to specific directory
    #   run: |
    #     mkdir -p path/to/desired/directory
    #     mv rol_parameters.xml path/to/desired/directory/

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add rol_parameters.xml  
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update ROL parameters XML" && git push)

