#! /usr/bin/env python

import sys
import os
import subprocess

trilinosDir = sys.argv[1]
packagesFile = os.path.join(trilinosDir, 'doc', 'DocumentingParameterLists',
	       'Packages.txt')
packages = open(packagesFile).readlines()

cmakeCommand = ['cmake',
		'-D TPL_ENABLE_MPI:BOOL=TRUE',
  		'-D Trilinos_ENABLE_TESTS:BOOL=OFF',
  		'-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF']

for package in packages:
    cmakeCommand.append('-D Trilinos_ENABLE_%s:BOOL=ON' % package)
    cmakeCommand.append('-D %s_ENABLE_TESTS:BOOL=ON' % package)

cmakeCommand.append(trilinosDir)

subprocess.call(cmakeCommand)

